### PR TITLE
Add missing inequality operator for table type (fixes #1159)

### LINKED ISSUE #1159: E2: Add inequality operator (!=) for table
Apparently, there is `==`, but no `!=` operator for table.
[Source](https://github.com/wiremod/wire/blob/c25f642c3bec03261b2ba7354000f21fdd3bb095/lua/entities/gmod_wire_expression2/core/table.lua#L281-L283).

### PR DESCRIPTION
**Pull request by CaptainPRICE**
Fixes #1159

### CODE REVIEW

**Comment by TomyLobo** [comment]
yeah, ~= is the standard lua way, good spot
I'd say merge

**Comment by oldmud0** [comment]
Looks like somebody forced push. Commit 5b7fd74f3cf521f7dfbdb41bdefb50ae039438ae is gone.

**Comment by TomyLobo** [comment]
that commit isnt in the wiremod/wire repo, meaning it very likely never was on any branch that still exists.

**Comment by CaptainPRICE** [comment]
@oldmud0 Yep I had it stuck there too, just marked it as read and it disappeared.

**Pull request merged**
