### PR TITLE
E2 Permissions Escalation Fix and `@disabled` rework

### PR DESCRIPTION
**Pull request by Derpius**
This reimplements my original perms escalation fix from last year, and improves upon `@disabled` by turning it into a preprocessor form of `error()`.

It also adds the directive when an E2 is pasted from a dupe that has code authored by someone other than the player duplicating.

Additionally, I saw that `:SetPlayer()` wasn't being called from the `Wire_Expression2_Player_Authed` hook while I was searching for all instances of setting `chip.player` so I've added a call to it there.

~~Still a draft as I need to implement the two owners into both the tooltip and remote uploader, and I need to test the dupe protection in multiplayer~~

### CODE REVIEW

**Comment by Derpius** [comment]
@Anticept should the world overlay even display the CPPI owner?

**Comment by InfHorus** [comment]
Are we done with garbage updates that are insanely pointless and break things more than they improve e2.

**Comment by Derpius** [comment]
@InfHorus whether you’re referring to `@disabled` or my changes, that’s not constructive criticism and cannot be used by anyone

**Comment by Anticept** [comment]
> @Anticept should the world overlay even display the CPPI owner?
> 
> All prop protection addons I've used have some form of HUD overlay already

Part of the reason I suggest this is to communicate to everyone that it is possible for the owner of a chip, and the owner of the code that runs on the chip, to be different.

As it stands right now, nothing does this in wiremod, so it's a paradigm shift.

As another point to make, if someone uploads code to an E2, it's going to act on them and not the chip owner right? Prop protection or not, this is another way to help people understand what is going on.

**Comment by Derpius** [comment]
This will mean updating the base world overlay to use CPPI owner with a fallback to sandbox's `GetPlayer`
I could put the CPPI owner in the E2 specific overlay and have the base owner name be the code author, but given it's next to the entity name that would probably cause confusion

**Comment by Derpius** [comment]
One other thing, I'm going to rename `@disabled` to `@error` cause I noticed that it works as a compile time error directive now, even showing in editor
image

**Comment by Derpius** [comment]
Just tested in multiplayer, all works

**Comment by Derpius** [comment]
Replaced `@disabled` directive with `#error` and improved the syntax highlighting of preprocessor commands to boot
image

This also allows for easy addition of `#warning` when @Vurv78 gets around to adding warnings to the preprocessor

**Comment by Derpius** [comment]
Tested the UI in singleplayer and multiplayer both with and without CPPI implementing addons

**Review by Vurv78 — APPROVED** [review]

**Pull request merged**
