### PR TITLE
Clean up and update text editor UI.

### PR DESCRIPTION
**Pull request by AbigailBuccaneer**
image

* Changed the text editor to use the default UI.
* Made the browser-editor divide draggable (instead of adjustable with a slider in the settings)
* Made the window buttons a lot prettier

This is a big pile of changes so that it's easier to tell what's going on in this otherwise huge change - when it's time to merge this I'll most likely `git merge --squash` by hand though.

### CODE REVIEW

**Comment by Divran** [comment]
:+1:

**Comment by Nebual** [comment]
Very nice, huge improvement! You've also fixed the Remote Uploader tab needing to be opened twice. 

Comparison

I think you could just keep the separate commits.

**Comment by Xandaros** [comment]
> I think you could just keep the separate commits.

I think he _should_ keep the separate commits. One logical change per commit. "Clean up and update text editor UI" is not one logical change. It even has an "and" in it :)

Looks like you decluttered the code quite a bit. I hope the changes won't break the starfall editor, though :)

**Comment by AbigailBuccaneer** [comment]
Yeah, in retrospect, it's not as many commits as it felt like, keeping them as separate commits makes more sense.

(you'd think that people would stop calling me "he" if i put my real first name in my username, right? ...)

**Comment by Xandaros** [comment]
@AbigailBuccaneer Male until proven otherwise, but I can call you "it", if you prefer :P

Sorry

**Comment by AbigailBuccaneer** [comment]
Well, if somebody had any strong feelings about this PR they'd have expressed them by now.

**Comment by Divran** [comment]
brace for deep noob complaint impact

**Comment by awilliamson** [comment]
I'm pretty sure it broke the starfall editor, not massively. Haven't bothered investigating it just yet, rolled back to before the commit this was merged.

**Comment by thegrb93** [comment]
starfall is depreciated anyway isn't it? At least I think expadv2 is replacing it.

**Comment by Divran** [comment]
@thegrb93 what? no? Starfall isn't even done yet (work is going much slower than expadv), and they're made by completely different people.

**Comment by AbigailBuccaneer** [comment]
While we're talking about replacing E2: I've already got secret plans for an Expression³ language! (See I've even got the name stylisation sorted).

**Comment by Xandaros** [comment]
Actually, a well designed compiled language might be faster than starfall, since you can get rid of a lot of runtime overhead. Getting the rich language featured of Lua in a custom language is going to be a hell of a lot of work, though.
(And looking at the direction Rusketh is going, I don't think it's going to be as comfortable to use, but that is just my (possibly biased) opinion)

Also, he said depreciated, not deprecated. He might mean deprecated, since it is a common misspelling, but depreciated is actually a word.
Assuming he actually meant depreciated: No, I don't think so. Starfall is not released yet, so it is difficult to tell how "valuable" it is or what people think of it, but whenever I show off what you can do with SF, people are amazed. It is just a fact of people not knowing about it or that it is still under development and was not abandoned. (Well, it was abandoned by col32 and then picked up again by divran and awilliamson)

Combining my two points, this Expression³ might actually be a good replacement of both, _if_ it is done right.

Well, that's enough off-topic, I think :D

**Pull request merged**
