### PR TITLE
Fix all git whitespace errors

### PR DESCRIPTION
**Pull request by AbigailBuccaneer**
This can be verified by `git diff --check`ing the entire tree:
```
# prints all whitespace errors according to git:
git diff-tree --check $(git hash-object -t tree /dev/null) whitespace
```

This should reduce the amount of Travis failures and reduce the amount of messy extra lines in diffs caused by people's editors automatically stripping trailing whitespace and doing other weird things because of it.

The underlying reason for git to consider these scenarios (trailing whitespace, blank lines at EOF, no newline at EOF, space-before-tab in indentation) as errors is because they don't play nicely in diffs, so it's typically better to just go ahead and agree with what Git thinks is a whitespace error.

### CODE REVIEW

**Comment by TomyLobo** [comment]
Does it still work?

**Comment by AbigailBuccaneer** [comment]
You know I don't like to test my pull requests @TomyLobo :wink:

**Comment by TomyLobo** [comment]
Yeah and you know what I think about that :)

**Comment by Nebual** [comment]
Rather than change a bunch of lines and cause a bunch of meaningless merge conflicts, lets just change our `git diff --check` settings to ignore whitespace :)

I'll close this due to its, ahem, conflicts.

**Pull request closed without merging**
