### PR TITLE
more models + modelplug cleanup

### PR DESCRIPTION
**Pull request by Fasteroid**
## More Models + Modelplug Cleanup
This PR gives a much-needed refactoring to `cl_modelplug.lua` and removes some redundant legacy sanity tests.
It also adds some new models I made, because hell, when have we last gotten new models?
### New Models
image
LEDs (in normal, mini, and nano, for wire lights)
Computer Fan (has skins, is animated, thruster and forcer)
Pointer Hand (has skins, a funny model for gimbals)

Publishing this as a draft for now—more good ideas are still to be had.
Looking forward to hearing feedback from the community.

### CODE REVIEW

**Comment by Fasteroid** [comment]
image
new inductor model

**Comment by Fasteroid** [comment]
Setting this back to draft so I can add some new cable types to wire plug (Like USB-C)

**Comment by Fasteroid** [comment]
> Can't you do a new PR?

would prefer this to be a one-and-done thing since new models will require a workshop update

**Comment by thegrb93** [comment]
K

**Comment by Fasteroid** [comment]
image

**Comment by Fasteroid** [comment]
Marking this as ready since I'm done making new models for now.  If anyone has special requests please ask and I'll make them.

**Comment by Fasteroid** [comment]
Not lint fixing motor since I didn't touch it in this commit.

**Review by thegrb93 — APPROVED** [review]

**Comment by thegrb93** [comment]
@Vurv78 Will need a workshop update after this one gets merged

**Comment by Fasteroid** [comment]
> @Vurv78 Will need a workshop update after this one gets merged

Perfect time to test the workshop auto-update actions

**Pull request merged**
