### PR TITLE
Change deprecated network functions to new ones

### PR DESCRIPTION
**Pull request by its-suun**
- Changed [Entity:SetNetworkedString](http://wiki.garrysmod.com/page/Entity/SetNetworkedString) to [Entity:SetNWString](http://wiki.garrysmod.com/page/Entity/SetNWString)
- Changed [Entity:GetNetworkedString](http://wiki.garrysmod.com/page/Entity/GetNetworkedString) to [Entity:GetNWString](http://wiki.garrysmod.com/page/Entity/GetNWString)

Also removed trailing whitespace and lines with space only accidently. If it's somehow a big issue I'll remake the commit.

### CODE REVIEW

**Comment by CaptainPRICE** [comment]
> Also removed trailing whitespace and lines with space only accidently. If it's somehow a big issue I'll remake the commit.

It shouldn't be an issue, thanks for cleaning it up. For those who use GitHub diff, use [this page](https://github.com/wiremod/wire/pull/1249/files?w=1).

**Comment by AbigailBuccaneer** [comment]
@CaptainPRICE that's incorrect. The coding style explicitly says:
> Your code shouldn't have trailing whitespace, and your editor should be configured to either do no cleanup or to follow this code style guide in order to avoid making your diff messy. The diff should only touch the code that's actually relevant.

**Comment by its-suun** [comment]
So .. remake?

**Comment by CaptainPRICE** [comment]
> and your editor should be configured to either do no cleanup _**or**_ to follow this code style guide in order _**to avoid making your diff messy**_

But, diff isn't messy, it is clear what has been changed. And I don't see any problems here; LGTM.

**Comment by oldmud0** [comment]
> But, diff isn't messy, it is clear what has been changed.
Please read the title of the PR. It says "Change deprecated network functions to new ones." I don't see anything that says "Cleanup whitespace" or "Remove stray tabs."

Unless the commit is *intentionally dedicated* to cleaning up code/whitespace, whitespace-related changes should not exist at all.

**Comment by AbigailBuccaneer** [comment]
@its-suun it'd be less controversial if you did. Thank you :smile:

**Comment by its-suun** [comment]
Done

**Comment by its-suun** [comment]
Merge?

**Pull request merged**
