### PR TITLE
Add more Wiremod EGP fonts

### PR DESCRIPTION
**Pull request by GamesArsenal96**
Hello Divran,

I have been noticing that Wiremod doesn't have all acquired fonts for EGP. Why?
I have already coded Wiremod and added them, but it only works on client/singleplayer. Is there anyway you can add it to the official Wiremod workshop addon so it works on all servers?

Edited [Wiremod/lua/entities/gmod_wire_egp/lib/egplib/materials.lua] file

https://www.dropbox.com/s/w4ok8f67fb75vm8/materials.lua?dl=1

If you can update the file that would be awesome so multiple servers can use multiple fonts :)

### CODE REVIEW

**Comment by Divran** [comment]
what the heck is this

**Comment by GamesArsenal96** [comment]
I never made a pull request before

**Comment by GamesArsenal96** [comment]
Close this one

**Comment by GamesArsenal96** [comment]
Sorry for wasting your time

**Pull request closed without merging**
