### PR TITLE
Remove beam netvars (leftover from #969)

### PR DESCRIPTION
**Pull request by CaptainPRICE**
Trash it. Because, it is completely unused.

### CODE REVIEW

**Comment by thegrb93** [comment]
ACF and other mods still uses it lmao

**Comment by thegrb93** [comment]
I'd be fine removing it tbh, but it just is easier for everyone if it stays

**Comment by CaptainPRICE** [comment]
imo, should be put into a separate addon (and repository) then... or maybe just move it into wire-extras.
If meant to keep the file here, then should place a note on the top of the file too.

**Comment by thegrb93** [comment]
I agree, but it is easier for everyone if it stays. Also I think wire-extras also depends on it too now that you mention it.

**Comment by TwistedTail** [comment]
Checked last night if it was indeed used by either ACF or Wire Extras and I couldn't find anything. I know ACF Missiles uses it but they decided to just get its own version of BeamNetVars back on 2016 when it was first considered to remove this file.

**Comment by thegrb93** [comment]
Lol instead of fixing their code they just copied the dependency. I guess we can remove it then.

**Pull request merged**
