### PR TITLE
Add entityDamage event and `damage` type

### LINKED ISSUE #2623: Add native damage detecting events to E2
im requesting to add a damage event so if the e2 or a prop takes damage the damage event acts like a wire damage detector. im creating a big project and need something like this so it can be done (its a prop damage system but with no addons)
like damagecore

`#somehing like this`

`if(Prop:damage <= 45)`
`{`
`#do something`
`}`

`#or in my case`

`if(Prop:iswelded)`
`{`
 `     if(Prop:damaged  == 1)#you can changed damage to damaged or whatever you would like`
   `   {`
    `          #do something`
`      }`
`}`

`#if you do decide to add this please make it so it can be effected by explosions, bullets, physics props being thrown at it, etc`

### PR DESCRIPTION
**Pull request by Vurv78**
Adds a damage event and damage type, nearly making `damagecore` obsolete.

It doesn't provide any of the `CDamageTypeInfo` setter methods or any form of damage inflicting methods to entity. That could be done in another PR.

It is disabled by default.

Fixes #2623

```golo
event entityDamage(Victim:entity, Damage:damage) {
    print(Victim, Damage:isType(_DMG_BLAST))
}
```

RFC:
* Any potential better names than `entityDamage`?
* Any potential better method names? (Kind of torn on `isType`)
* Should it be disabled by default?

### CODE REVIEW

**Comment by wrefgtzweve** [comment]
entityDamage sounds pretty good, maybe onEntityDamage of some sort could work?
The constants might be vague for people as (as far as i know) people rarely use constants in e2 however, something like dmg:IsBlast() might also be annoying, though  i feel like the latter might work better for the average e2 person.
Having a core option like propcore that's disabled by default would be appreciated yes.

**Comment by Vurv78** [comment]
> The constants might be vague for people as (as far as i know) people rarely use constants in e2 however, something like dmg:IsBlast() might also be annoying, though i feel like the latter might work better for the average e2 person.

I could add these, but I mean I don't think doing `dmg:isType(_DMG_BLAST)` instead of `dmg:isBlast()` is that bad.

I went for the `isType` approach since the wiki discourages use of `dmg:GetDamageType()` and E2 users wouldn't know what to do with it

**Comment by thegrb93** [comment]
Probably just needs helper entries, right?

**Comment by Vurv78** [comment]
I knew there was something missing, thanks

**Review by thegrb93 — APPROVED** [review]

**Comment by Vurv78** [comment]
I'll add the `isBlast` etc methods if there are enough people confused about `isType` in the discord or whatever.

**Comment by DecVes** [comment]
i would make it enabled by default and if the server wants to not have it then disable it

**Pull request merged**
