### PR TITLE
Fix #1877

### LINKED ISSUE #1877: E2: Entity search/find is broken
Running on the latest wire (as of the date of this post):
> Wiremod's version: 'Git c77e70c'

Having only wire addon installed, something is weird about entity search/find in E2.
For example:
1. Start a new singleplayer Sandbox game (there are no wire entities spawned).
2. Spawn the following E2 chip/code:
    ```golo
    if (!findCanQuery()) {
        reset()
        exit()
    }
    
    findByClass(entity():type()) # Find all E2 (gmod_wire_expression2) entities.
    
    local E2s = findToArray()
    print("#Array = " + E2s:count()) # Print out status (first is: "#Array = 0")
    print(findResult(1):isValid() ? "Ok." : "NOT OK!") # Prints "NOT OK!", even without calling isValid.
    ```
3. Notice `#Array` started to increment from 0. But, it should have printed `1`.
4. Spawn more of those E2s, and it will start to increment `#Array`, but always missing that 1.

Something is just quite wrong... I have also tried to iterate the found entities:
```golo
foreach (K, V:entity = E2s) { print(format("E2 (#%d) found: %s", V:id(), V:getName())) }
```
I have noticed that nothing is being printed with only 1 chip, so, as before after spawning in an another chip, then it started to run the print inside foreach-loop.

### PR DESCRIPTION
**Pull request by Plootie**
Addresses issue #1877 which appears to have come from `E2Lib.filterList`

### CODE REVIEW

**Comment by TomyLobo** [comment]
I don't see how.
All you have changed is that the list no longer modifies its input list.
Can you show how that fixes anything?
Can you also check if anything depends on the input list being filtered as well?

**Comment by CaptainPRICE** [comment]
I'll go check this out, let me test it.

**Comment by TomyLobo** [comment]
Yeah there is code in find.lua that depends on the input list being filtered.
So yeah, you fixed the problem by killing filtering altogether :)

**Comment by Plootie** [comment]
Ah... yeah thats my bad, i didn't check that before making the pr, sorry about that. I'll make a new commit to fix it :P

**Comment by CaptainPRICE** [comment]
@TomyLobo Yeah, I think the same, the `list` is to be modified there, not create a new table (because a return value is unused, it is a `list` reference which should be modified).

**Comment by Plootie** [comment]
see #1877 comments

**Pull request closed without merging**
