### PR TITLE
Add linear interpolation (LERP) for quats

### PR DESCRIPTION
**Pull request by Kamilczak020**
Introducing Quaternion LERP as there is SLERP already. No need for NLERP since its just LERP result normalized. Haven't done e2helper desc yet.

### CODE REVIEW

**Comment by TomyLobo** [comment]
what is LERP needed for?

**Comment by Divran** [comment]
If I understand it correctly, slerp speeds up, reaches a max speed, and then slows down again. Lerp, on the other hand, rotates/moves stuff at a constant speed.

**Comment by TomyLobo** [comment]
slerp is spherical linear interpolation. it's linear on a sphere.
In other words, if anything, it's the other way round.

But I was asking @Kamilczak020 :)

**Comment by Divran** [comment]
but I've used slerp in gmod many times and it does speed up, reach a top speed, and then slow down, if provided with a constant multiplier. You have to change the multiplier a lot to get it to be the same speed throughout the whole rotation.

**Comment by thegrb93** [comment]
>From wikipedia "When Slerp is applied to unit quaternions, the quaternion path maps to a path through 3D rotations in a standard way. The effect is a rotation with uniform angular velocity around a fixed rotation axis"

**Comment by Divran** [comment]
In that case, slerp is implemented incorrectly.

**Comment by TomyLobo** [comment]
then it should be fixed.

...so the question still stands: what is LERP used for?

**Comment by AbigailBuccaneer** [comment]
http://number-none.com/product/Understanding%20Slerp,%20Then%20Not%20Using%20It/ This is a good article that gives more info about slerp and similar. (Formatting's a bit broken though.)

**Comment by TomyLobo** [comment]
I'm missing the logs in this log-quaternion lerp

**Comment by TomyLobo** [comment]
In conclusion, let's have slerp, nlerp and lqlerp functions
having lerp might cause people to use that and wonder why those stupid useless quaternions are broken and useless

**Comment by oldmud0** [comment]
Merge?

**Comment by AbigailBuccaneer** [comment]
This needs an E2Helper description, and I won't be home tonight. Happy for this to be merged if somebody can immediately follow it up with adding the description.

**Comment by AbigailBuccaneer** [comment]
(If anybody's curious about the implementation, I was looking up a reference implementation and ended up [here](http://www.3dkingdoms.com/weekly/quat.h), where the code seems to have been translated from.)

**Comment by oldmud0** [comment]
I should read up on quats one day.

**Pull request merged**
