### PR TITLE
Ported Wireman to AdvDupe2 and fixed its E2

### LINKED ISSUE #644: Wireman's E2 is garbled after the .txt workaround
After wireman is unpacked from the default_data_thingy, newlines and quotes are messed up. Using the wireman.txt straight from the repo works fine.

The file default_data_thingy unpacks: https://dl.dropboxusercontent.com/u/12612176/wireman/wireman_garbled.txt
The way it is in the repo: https://dl.dropboxusercontent.com/u/12612176/wireman/wireman_repo.txt

The view in E2: https://dl.dropboxusercontent.com/u/12612176/pics/wireman_noooo.png

I can't even gmod without wireman...

### PR DESCRIPTION
**Pull request by CaptainPRICE**
Fixes #644

### CODE REVIEW

**Comment by TomyLobo** [comment]
Why is that binary?

**Comment by CaptainPRICE** [comment]
@TomyLobo I don't know why would you ask such a question.
It is recognized as binary file by GitHub. I don't know what else to tell you, nothing I can do... Any Advanced Duplicator 2 file is treated as binary file on GitHub...

**Comment by oldmud0** [comment]
Because it contains non-textual data, and we all know only GLON would do such a horrid thing as that...

**Comment by TomyLobo** [comment]
Well someone obviously didnt think things through when designing advdupe2...
The tiny amounts of space you save when storing those dupes are not worth the obfuscation, much less with a proprietary format like that.

Compressing for transfer, that's a different story and could be done on the fly.

**Comment by CaptainPRICE** [comment]
@oldmud0
> we all know only GLON would do such a horrid thing as that

If you think advdupe2 uses GLON, you're wrong then. From what I see ([here](https://github.com/wiremod/advdupe2/blob/457c6d050f56fe0f942c1970dcfb43ee092c1e9a/lua/advdupe2/sh_codec.lua#L390-L398)), it uses [FastLZ](http://fastlz.org/) algorithm for compression of serialized dupe data..

**Comment by oldmud0** [comment]
I'm always wrong, so might as well ban me.

**Comment by chinoto** [comment]
@oldmud0: You're right for the wrong reason.

**Comment by AbigailBuccaneer** [comment]
Is there any advantage to using AdvDupe2 for this? (Wiremod only adopted development of AdvDupe2 because it was abandoned and we needed to fix things in it to be able to clean up AdvDupe2-specific hacks in Wiremod without people complaining at us.)

**Comment by CaptainPRICE** [comment]
Current Wireman (AdvDupe1) is broken. This fixes its broken E2, and upgrades it to AdvDupe2. :dancer:

**Comment by TomyLobo** [comment]
That is not an upgrade. AdvDupe and AdvDupe2, despite their names, are separate add-ons.

**Comment by CaptainPRICE** [comment]
> AdvDupe and AdvDupe2, despite their names, are separate add-ons.

Can you tell me what is Wireman doing here?

**Pull request merged**
