### PR TITLE
FLIR Fix

### PR DESCRIPTION
**Pull request by Hazeofdream**
Removed FLIR rendering invisible entities.

Since we aren't close to doing the 'heat signature strength' that is put in the comments at the top, at the very least things that shouldn't be rendered are fixed here. alot of wire contraptions will appreciate this i imagine.

### CODE REVIEW

**Comment by thegrb93** [comment]
Could you add it to the other if statement instead of making a new if statement

**Comment by Hazeofdream** [comment]
Done.

**Comment by Hazeofdream** [comment]
ACTUALLY done this time, gaining github experience once update at a time lmao

**Comment by thegrb93** [comment]
Thx

**Pull request merged**
