### PR TITLE
Remove debug PrintTable

### PR DESCRIPTION
**Pull request by Python1320**
can be used to spam server console

### CODE REVIEW

**Comment by bigdogmat** [comment]
This isn't for debug. We overwrite `Msg` because that's what `PrintTable` uses to print out the array, we then use what was captured in `Msg` and print that out in chat.

**Comment by Divran** [comment]
We can't accept this PR because it would make printTable in E2 stop working (they'd do nothing). Like bigdogmat said, if you for some reason need this function to stop using an overwritten PrintTable, we can definitely accept a PR that changes it to use its own internal function.

**Comment by thegrb93** [comment]
Or rewrite it so that it uses the PrintTable source instead of overriding Msg.

**Comment by TomyLobo** [comment]
I think a solution should be sought upstream.
PrintTable simply has no way to specify an alternative target than Msg.

**Comment by bigdogmat** [comment]
> PrintTable simply has no way to specify an alternative target than Msg.

If an addon overwrites it (Example #1307), or if it's changed within Gmod.

**Comment by TomyLobo** [comment]
@bigdogmat that is what I meant by "a solution should be sought upstream".

**Pull request closed without merging**
