### PR TITLE
Add custom background colors to E2 editor

### PR DESCRIPTION
**Pull request by Aws0mee**
I'd like to see this change added, because I think custom backgrounds would be pretty cool.

I did the changes requested by @Vurv78 in @RadioActvePixels's original PR. Additionally, I resolved the merge conflicts from the stale PR. Let me know if any additional changes should be made.

image

Credits to @RadioActvePixels for the original PR: #2439
Fixes https://github.com/wiremod/wire/issues/1126

### CODE REVIEW

**Comment by Vurv78** [comment]
I think some people would want to customize the gutter rather than having it be relative to background, but should be fine as is right now

**Comment by Aws0mee** [comment]
> I think some people would want to customize the gutter rather than having it be relative to background, but should be fine as is right now

Alright, let me know if you want any changes or feel free to make them yourself.

**Comment by Vurv78** [comment]
Merging but just for the record I'd prefer the least amount of logic possible in the render hook, even if it's just adding to the components of the color, would be a bit annoying to implement though with the current customization system

**Comment by Aws0mee** [comment]
> Merging but just for the record I'd prefer the least amount of logic possible in the render hook, even if it's just adding to the components of the color, would be a bit annoying to implement though with the current customization system

We can make improvements in the future hopefully.

**Pull request merged**
