### PR TITLE
Add new damage types to the Damage Detector

### PR DESCRIPTION
**Pull request by marchkarcz**
Instead of just Explosive, Bullet, Melee, Fall, and Crush, this would add a good majority of the damage types seen here: https://wiki.garrysmod.com/page/Enums/DMG

This would help for damage detection E2's and properly nerfing/buffing certain weaknesses more accurately.

### CODE REVIEW

**Comment by thegrb93** [comment]
Could you change it to use this style?

```lua
--Before the UpdateDamage function
local damageTypes = {
	[DMG_CRUSH] = "Crush",
	[DMG_BULLET] = "Bullet"
}

--Inside the UpdateDamage function
self.dmgtype = damageTypes[CTakeDamageInfo:GetDamageType()] or "Other"
```

**Comment by marchkarcz** [comment]
Done

**Comment by marchkarcz** [comment]
Anything else I should do?

**Comment by thegrb93** [comment]
Looks good to me, just have to make sure it works.

**Comment by marchkarcz** [comment]
Alright.

**Pull request merged**
