### PR TITLE
Fix light sprite size

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #2200

### CODE REVIEW

**Comment by sammyt291** [comment]
The sprite can only size to 128 as its max is seems

**Comment by thegrb93** [comment]
It's working for me. Try again? If not, let me know how you're doing it.

**Comment by thegrb93** [comment]
@sammyt291

**Comment by bellum128** [comment]
Oh I was checking the issue instead of the PR. This all looks great, thanks a lot!

**Pull request merged**
