### PR TITLE
Do not highlight UDFs after preprocessor commands

### LINKED ISSUE #1755: Syntax highlighting for #ifdef seems borked
Running off [`Wiremod's version: 'Git 84dcff6'`](https://github.com/wiremod/wire/commit/84dcff60b377d214b4af4ddce43dc57405312bfc).
(Garry's Mod version: `2018.10.10` - current public branch)

Here is a screenshot of how it looks like (given that, all of the builtin extensions are disabled/off):
Screenshot

See, `effect()` is highlighted red as there is no such function, but what's up with `ranger(number)`?!
There is no `ranger(n)` function in E2Helper, of course because `ranger` extension is disabled. But, why is it colored differently then?

Also, you can observe how it picks up the color of UDF. It just makes confusion. `#ifdef` doesn't even work for UDFs, because it is not even intended to. So, why does it color them?

Syntax highlighter seems borked, and should be cleaned up.

### PR DESCRIPTION
**Pull request by TomyLobo**
I had to fix the indentation before fixing this, thanks @AbigailBuccaneer :)

Someone needs to test this before merging, btw, since I haven't even started up gmod or any Lua interpreter at all for this.

Fixes #1755

### CODE REVIEW

**Comment by thegrb93** [comment]
Can you also provide info on how to test this?

**Comment by thegrb93** [comment]
@TomyLobo can you finish this PR? Idk if it's ready or what

**Comment by thegrb93** [comment]
Doesn't work

**Comment by TomyLobo** [comment]
Yeah, I have no idea how this works anymore. Doesn't seem like a big issue to me anyway. If I figure it out, I'll restore and reopen.

**Pull request closed without merging**
