### PR TITLE
Fix CPUs/OPS do not update after hitting limits

### PR DESCRIPTION
**Pull request by Aws0mee**
Attempt at fixing #2339 

This is a WIP.

Before:

image

After:

image

### CODE REVIEW

**Comment by InfHorus** [comment]
Never been an issue, would be great to ensure issues you're fixing are actual globalized issues and not random issues caused by your setup
image

**Comment by thegrb93** [comment]
I don't think you should have the limit check and error call in that function. It should just update the numbers.

**Comment by InfHorus** [comment]
Never been an issue, would be great to ensure stuff that you fix are globalized issues and not random issues from your server setup only.

image

**Comment by Aws0mee** [comment]
> I don't think you should have the limit check and error call in that function. It should just update the numbers.

Okay, I'll change that when I get a chance.

**Comment by Aws0mee** [comment]
Tested on my private server, seems to work.

**Comment by Vurv78** [comment]
You overwrote all of the event changes when fixing merge conflicts

**Comment by Aws0mee** [comment]
> You overwrote all of the event changes when fixing merge conflicts

Not sure how that happened, I'll fix this soon.

**Comment by Aws0mee** [comment]
Works on my test server, but this time does not overwrite the entire event system.

**Pull request merged**
