### PR TITLE
fix serverside EGP.ScrHW memory leak

### PR DESCRIPTION
**Pull request by storm37000**
This fixes NULL players filling up in the EGP.ScrHW table by simply storing it on the player entity instead.  Then it will be auto removed when the player leaves.

Example snippet of what im fixing:
```
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1366
                                2       =       768
                Player [NULL]:
                                1       =       3840
                                2       =       2160
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1280
                                2       =       720
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
                Player [NULL]:
                                1       =       1920
                                2       =       1080
```

### CODE REVIEW

**Comment by TomyLobo** [comment]
I'd rather avoid storing things directly in the player table.
Other parts of Wiremod also store things for players.
See how they clean it up.

**Comment by TomyLobo** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp/lib/egplib/framecontrol.lua turns out, they don't :D

**Comment by TomyLobo** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_egp/lib/egplib/transmitreceive.lua#L15 here's one that does clean up.
No idea why that's a : call though, since self isn't used anywhere there.
anyway, how about this:
Create WireLib.PlayerTables and add EGP.ScrHW, EGP.Frames, EGP.IntervalCheck, EGP.Queue and whatever else you may find to it under their own key each.
Then move that disconnect hook that I linked above to WireLib and have it loop through WireLib.PlayerTables and clean out the disconnected player from every table that's registered there.

**Comment by TomyLobo** [comment]
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/files.lua#L25-L28 here are some more you could add.

**Comment by TomyLobo** [comment]
For convenience, you can make a WireLib.RegisterPlayerTable function that creates a table, registers it and returns it.
Here's a draft of what I mean:
```lua
WireLib.PlayerTables = setmetatable({}, {__mode = "kv"})

function WireLib.RegisterPlayerTable(tbl)
    tbl = tbl or {}
    WireLib.PlayerTables[tbl] = tbl
    return tbl
end
```
Usage:
```lua
EGP.ScrHW = WireLib.RegisterPlayerTable()
```

**Comment by thegrb93** [comment]
Why bother over-complicating it when lua handles all that for you after the player table __gcs.

**Review by thegrb93 — APPROVED** [review]
lgtm

**Comment by TomyLobo** [comment]
@thegrb93 as i've demonstrated, we have a ton of these tables and most of them lack cleanup. Do you want them all in the player table?

**Comment by thegrb93** [comment]
That'd be fine yeah. That's how advdupe2 does it.

**Comment by storm37000** [comment]
ill make a branch to fix the other memory leaks, but since this branch is only about EGP.ScrHW, I will leave it as is unless something isnt working, waiting for it to be merged.

**Comment by thegrb93** [comment]
Sounds good. just giving a bit of time before merging.

**Comment by TomyLobo** [comment]
@thegrb93 can you think of any disadvantages of having everything in the player table?

**Comment by thegrb93** [comment]
Performance, each index has to call Entity.__index unless you store Entity:GetTable() into a local and index that.

**Comment by thegrb93** [comment]
Entity.__index is a notoriously slow call

**Comment by storm37000** [comment]
i could put it back and see if a way could be made to remove players from the list as they leave?

**Comment by thegrb93** [comment]
We're talking nanoseconds. It is only bad if it is in realtime/high volume calls.

**Pull request merged**
