### PR TITLE
Use local variables to prevent overwriting the library address

### PR DESCRIPTION
**Pull request by dvdvideo1234**
That way the "constraint" library will not be overriden

### CODE REVIEW

**Comment by bigdogmat** [comment]
What? It's only overwritten in local scope, not global

**Comment by Divran** [comment]
yeah this changes nothing

**Comment by Nebual** [comment]
I believe his point is so constraint.Weld (L195) and constraint.Rope (L201), which are both in that scope, still have access to the global constraint library instead of the local variable.

**Comment by bigdogmat** [comment]
@Nebual The scope of both of those local variables isn't create until after those functions are executed

**Comment by dvdvideo1234** [comment]
@ Nebual That's correct, and it is not confusing that way

**Comment by Nebual** [comment]
Oops, missed the `else` - you're right this changes nothing (besides improving readability)

**Comment by TomyLobo** [comment]
Seriously, learn to scope...

**Comment by dvdvideo1234** [comment]
I've already learned it, and this looks confusing :D

**Pull request closed without merging**
