### PR TITLE
Add new GetFrictionSnapshot function

### PR DESCRIPTION
**Pull request by shadowscion**
https://wiki.facepunch.com/gmod/PhysObj:GetFrictionSnapshot

Returns information that might be useful for simulations. Per the wiki it returns a table of tables, but through testing I have not seen any setup that produces more than one. I left out t he surface info as I'm not entirely sure what that even is.

### CODE REVIEW

**Comment by thegrb93** [comment]
Needs a large ops consumption.

**Comment by shadowscion** [comment]
How large?

**Comment by thegrb93** [comment]
Id say `50 * #events` or `100 * #events`

**Comment by shadowscion** [comment]
Can you point me to another function that has varied op costs? I don't know how to do it.

**Review by thegrb93 — APPROVED** [review]

**Comment by thegrb93** [comment]
Thanks!

**Pull request merged**
