### PR TITLE
Added syntax highlighting support for HL-ZASM block comments.

### LINKED ISSUE #816: ZCPU Editor doesn't highlight block comments
Example code:
```
// This is a single-line comment

/* This is a single-line comment. Code gets highlighted inside block comments. */

/*
    This is
    a multi-line
    comment.


    Code gets highlighted inside block comments.
    
        mov ESI, text;
        mov EDI, 65536;
    main:
        cmp #ESI, 0;    je exit;    // Exit code if ESI points to a null char
        mov #EDI, #ESI; inc EDI;    // Write char to digital screen
        mov #EDI, 999;  inc EDI;    // Set color to white
        inc ESI;                    // Move to next char
        jmp main;
    exit: 
        int 2;                      // Send interrupt 2 (End of program execution)
    text:
        db "Hello world!", 0;
    
*/
```
Resulted highlighting:
Resulted highlighting

*Note that the ZASM code is ignored by the compiler because it's tokenized as a comment.*

### PR DESCRIPTION
**Pull request by immibis**
Fixes #816 - block comments are highlighted, with one exception (which should hopefully be minor):

If a `/*` is off the top of the visible screen, and inside a string, then the syntax highlighter will think it's a valid comment start. For example, in:

    "/*" // scroll so this line is invisible
    test // but this line is visible

`test` will be highlighted as a comment.

The E2 highlighter has a similar issue, and the root cause is the same - see #890.

### CODE REVIEW

**Comment by TomyLobo** [comment]
This looks insane, can you put this in a separate function please, @PhoenixBlack ?

**Comment by suunrider** [comment]
Why should it be put in a seperate function?

**Comment by immibis** [comment]
Black Phoenix is back?!

**Comment by TomyLobo** [comment]
@suunrider Hmm, you're right... I took a closer look, that editor needs some serious refactoring.
There's practically 3 classes in there waiting to get out:
- TextEditor
- Expression2Editor
- ZASMEditor

**Comment by suunrider** [comment]
@immibis, not really. I asked her on IRC to merge some pull requests here. But she doesnt have enough time to develop by herself on zcpu.

**Comment by TomyLobo** [comment]
"she"?
oh my, people change, i guess :D

**Comment by suunrider** [comment]
@TomyLobo what do you mean?

**Pull request merged**
