### PR TITLE
Fix issues with E2 user-defined functions

### PR DESCRIPTION
**Pull request by AbigailBuccaneer**
* Improve horrible code style
* Error at runtime if a function should return a value and it doesn't

### CODE REVIEW

**Comment by Divran** [comment]
Should this be merged?

**Comment by TomyLobo** [comment]
Glancing at it, I can't see what you changed in that first commit...
What happens if you have 2 arguments with the same name, pre- and post-patch?

**Comment by TomyLobo** [comment]
I'm going to try and split up your first commit into multiple parts, just for shits...

**Comment by TomyLobo** [comment]
Halt the presses! Something is not right. This "cleanup" commit changes which functions are called

**Comment by TomyLobo** [comment]
There, I split up your cleanup into smaller units and marked the objectionable parts accordingly.
@AbigailBuccaneer can you explain why each of the "Questionable" changes was made and why it doesn't break anything?

**Comment by TomyLobo** [comment]
@AbigailBuccaneer Can you address each of the commits I marked as "Useless: " or "Questionable: "?
For some, you can just copypaste what you wrote, but at least one is unaddressed

**Comment by Divran** [comment]
So should this be merged? @TomyLobo @AbigailBuccaneer

**Comment by AbigailBuccaneer** [comment]
There was a useful part of this but I mixed in changes to improve the code style, and then @TomyLobo exploded the commit into more. I'll make another PR that addresses the actual issue that this fixes.

**Comment by TomyLobo** [comment]
@AbigailBuccaneer make sure everyone can see at first glance what the actual change is :)

**Pull request closed without merging**
