### PR TITLE
Remove ZCPU/GPU/SPU

### PR DESCRIPTION
**Pull request by Vurv78**
Unfortunately the developer hasn't been active for the past decade or so, and they've been causing a lot more harm than good recently.

Hardly anyone uses them already.  
For those of you that do use it, currently trying to plan a new chip, or a rewrite at the very least, to replace it.

### CODE REVIEW

**Comment by yogwoggf** [comment]
Fine example of the wiremod project

**Comment by Grissess** [comment]
Oh, curses, there goes my childhood.

You got a branch or link to where this planned replacement is being developed? Zyelios was far from perfect (even if it was fun), and I'm hoping some of its mistakes can inform future decisions.

**Comment by possiblynova** [comment]
sorry i forgot to leave a comment in the 3 minute period between the PR submission and merge into master

**Comment by possiblynova** [comment]
don't forget that y'all *literally didn't test this*, since it disabled gpulib, which multiple screens from wire & others rely on??

**Comment by thegrb93** [comment]
why didn't they test every wire entity before merging?? 😭😭

**Comment by Vurv78** [comment]
> Oh, curses, there goes my childhood.
> 
> You got a branch or link to where this planned replacement is being developed? Zyelios was far from perfect (even if it was fun), and I'm hoping some of its mistakes can inform future decisions.

Not yet, no, It's still just barely being planned, I'm not the one working on it since I don't have any clue about this area of programming. So it could even just not happen entirely, maybe someone picks up development on the CPU and it thrives as a separate addon. You can still find the CPU/GPU/SPU at https://github.com/wiremod/wire-cpu.

My idea was always a webassembly / wasi chip, but I don't think that'd apply to the same audience.

**Comment by Grissess** [comment]
> My idea was always a webassembly / wasi chip, but I don't think that'd apply to the same audience.

WASI's not bad, but always intended to be an application interface; it intentionally omits complexity deemed suitable for a "supervisor"--the details of handling open file descriptions and memory, among other things.

I'm admitting bias in being fond of RISC-V--which has a similar base spec, but a "privileged" spec that details one way of going about low-level interfaces. Since this was practically the _raison d'être_ for HiSpeed, a low-level, MMIO-based approach (over FDs and assumptions of virtual memory) seems apropos. The ol' ZCPU, if I recall, saw its development heyday in implementing an old pluggable game console, for which BP put together a BIOS--that's my presumed target audience. (More dogmatically: if you want a scripting environment, use E2 :)

I was kinda hoping someone would have a Lua RISC-V emulator sitting around, but I'm not seeing one yet, especially not one that implements the privileged extensions. Oh well, I'll keep looking.

**Comment by Vurv78** [comment]
There are webassembly to lua compilers out there, if there's a riscv emulator that can compile to webassembly then could try and use it.

https://github.com/Rerumu/Wasynth

This is the cleanest implementation, however the luajit output needs the ffi library, unfortunately. Maybe could fork and tweak the Luau output.

**Comment by Grissess** [comment]
> There are webassembly to lua compilers out there, if there's a riscv emulator that can compile to webassembly then could try and use it.

I can't really recommend direct synthesis unless it includes a way to preempt it; Lua, on its own, does not implement preemption, and that's a really easy DoS vector for anything, real-time execution (in a game server thread) in particular. Zyelios did _something_ of this ilk in its "microcode" bits, but only "JITed" a fixed number of instructions (up to 8) into a chunk at a time, stopping early at any branch, thus allowing a driver routine to pause execution (in order to keep up with the tickrate, e.g.). Hardware designs where an RTL is already well-defined lend themselves to this naturally; WASM is technically not an exception, but--having looked into it for yet another game a year or two ago--support for preemption in modern runtimes is lacking in preference to performance.

**Pull request merged**
