### PR TITLE
Added some shader checks to e2 setMaterial

### PR DESCRIPTION
**Pull request by thegrb93**
Some materials can create odd rendering effects. This should keep all materials sane.

### CODE REVIEW

**Comment by Divran** [comment]
👍

**Comment by Divran** [comment]
man this sure was forgotten. Want me to merge it now or should I wait for you to add that other material in #1431

**Comment by thegrb93** [comment]
engine/writez uses the WriteZ_DX9 shader so it's already blocked.

**Comment by CaptainPRICE** [comment]
And... Legit uses of this are down as well. gj anyway.
@thegrb93 @Divran Request: Please create a serverside (toggle) ConVar for these checks..

**Comment by Divran** [comment]
What possible legit uses are there for breaking the game renderer?

**Comment by CaptainPRICE** [comment]
@Divran 
> What possible legit uses are there for breaking the game renderer?

It is NOT breaking the rendering at all, just changing how prop will be shown as (in material fashion). `engine/writez` allows for cool illusion (E2) games, and what not.
Here is just a quick screenshot (thanks to "ITAsimo456"):
engine/writez screenshot
That's not breaking or crashing the client in any way. So, please create a "whitelist", or, add ConVar (as I suggested above), or, revert the PR. The PR implementation doesn't make us all happy.
/change-requested

**Comment by Divran** [comment]
This PR doesn't block `engine/writez`.

**Comment by thegrb93** [comment]
Something tells me those "cool illusion" games can also be easily abused

**Comment by Kawoosh** [comment]
After wiremod update we found that setMaterial and setSubMaterial no longer works in E2 on the server. I found this commit and noticed that GetShader() returns "shader_error" on serverside for everything. 
Code for example
```lua
local Mat=Material("models/props_c17/furniturewooddrawers001a")
print(Mat:GetShader())
```
Prints "shader_error" on server and "VertexLitGeneric" on client. The server works on linux.
So it looks like this check is not a good idea.
And I think we need some convars to enable/disable so strong checks (similar to wire_holograms_modelany) for those who wants to give much free play for users.

**Comment by thegrb93** [comment]
It works correctly on my server though. Is your server missing the vmts?

**Comment by Kawoosh** [comment]
```lua
local Mat=Material("models/props_c17/furniturewooddrawers001a")
print(Mat:GetShader())
print(file.Read("materials/models/props_c17/furniturewooddrawers001a.vmt","GAME")) 
```
output:
```
shader_error
"VertexLitGeneric"
{
	"$basetexture" "Models/props_c17/FurnitureWoodDrawers001a"
	"$envmap" "env_cubemap"
	"$basealphaenvmapmask" 1
	
}
```
So.....

**Comment by thegrb93** [comment]
Linux bug I guess?

**Comment by Divran** [comment]
Maybe if we wrap it in pcall? And if it errors then we allow the material. Or maybe there's a way to get the name of the OS?

**Comment by Kawoosh** [comment]
It not throws errors, just returns "shader_error" string, so no need to use pcall here. There are system.IsLinux() and some similar functions, but it not looks good because these checks will work too different on different systems.
In any case it not looks a good idea to load materials at server that have not to work with graphics at all, it can waste resources for nothing.

**Comment by Divran** [comment]
but the server doesn't need the materials, only the clients do. If a user selects a material that the server doesn't have, then the server will return shader error or whatever, but the material might still be perfectly fine to use

**Comment by Kawoosh** [comment]
Yes, but Material() call may be loads material and allocates resources even on server... This needs some research to know. But anyway it's not a good idea to use something that not works everywhere correctly.

**Comment by Divran** [comment]
The reference to "Mat" disappears after the end of the function call, so the lua garbage collector will delete it. Won't this also unallocate any server resources that were allocated?

**Comment by thegrb93** [comment]
IMaterial is only maybe around 100 bytes anyway.

**Comment by Divran** [comment]
If you're sure it works that way. No point in reporting it on the gmod repo if it isn't actually an issue

**Comment by adosikas** [comment]
Its broken on the server I play on as well (also linux host).

Can we revert this for now?

Breaking all materials is kinda a big deal.

**Comment by thegrb93** [comment]
Just put `if system.IsLinux() then return material end` on line 52

**Comment by Kawoosh** [comment]
And then users will be confused why their code works on some servers and not works on others. It's too dirty solution. Any code that can't work on all systems with equal result should be discarded.
I made some performance tests. First loading of 200 materials took 2 seconds (and server freezes for that time), so `Material()` is not so easy operation. Resources can be used on engine level, and Lua garbage collector may not affect it.

**Comment by thegrb93** [comment]
SetMaterial isn't cheap either. And if you're using materials with shaders not in the whitelist, you're doing something wrong anyway. The only difference is linux servers won't be able to block them.

**Comment by Kawoosh** [comment]
It was cheap for the server. I see no reason to do such excessive load on server just because someone was trolled with wrong material. Our server works wth only 1GB of ram. Anyway if you want this code, it should be used with ConVar and not enabled by default because of unstability and waste of resources.

**Comment by Divran** [comment]
If the `Material` function is both expensive and doesn't work on linux then I agree that it should be removed. If there are any known materials that can be abused, @thegrb93 you can add direct string comparisons for them just like `pp/copy` instead. That will use no resources at all. It won't be as secure, but it'll have to do.

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/1439

**Pull request merged**
