### PR TITLE
Revert "Changed DHDD's array output to a "proxy" array"

### LINKED ISSUE #1091: DHDD not output anything?
I wrote array in a dhdd and it shows to be of the size 2 but it's writing an empty array to the Memory Output? Am i doing something wrong?
dhdd

### PR DESCRIPTION
**Pull request by TomyLobo**
Reverts wiremod/wire#962

Fixes #1091

Is a replacement for this really needed?
Can't we just update it periodically in Think if AllowWrite is true?
I think this whole AllowWrite feature is a mistake, btw and we should deprecate it somehow.

### CODE REVIEW

**Comment by bigdogmat** [comment]
I don't really see a reason for AllowWrite unless you have multiple things writing cells at a time. I may be wrong though I don't get the use case of it.

**Comment by TomyLobo** [comment]
Well, you still have wirelink's highspeed capabilities.
Doesn't DHDD have highspeed support?
I don't actually know what DHDD is, btw

**Comment by Divran** [comment]
it was supposed to be a simple and easy to use hard drive that saves its
data in the dupe file, but I dunno where it's mutated off to now

**Comment by oldmud0** [comment]
It used to be "dupable HDD" but now it's turned into "deprecated HDD"

**Comment by oninoni** [comment]
Actually i found out you can easily use it by just accesing the Memory via Wirelink:

wirelink[Adress]

So it is very simple to use :D

**Comment by oldmud0** [comment]
Yeah, that's how you access a lot of High Speed entities by wirelink, just accessing them as if they were an array.

**Comment by oninoni** [comment]
Then the main problem is that the wiki is not up to date...

**Comment by bigdogmat** [comment]
@oninoni The wiki has almost never been up to date, @suunrider afaik is in the process of converting it to the github wiki. 

Also the main problem here isn't that as you can figure that out by looking through the forums or probably some tutorials. The main problem is that the way this tool is coded atm makes the debugger tool and E2 arrays "bug".

**Comment by oldmud0** [comment]
To be honest, accessing High Speed wirelink should never have been by array. People should have been forced to use helper functions instead like `write()` or `read()`.

**Comment by suunrider** [comment]
Yes, im making the wiki, soon (e2 wiki is much). If there was a better difference between high speed and wirelink, then `wire` and `read` would be really useful. Not only the syntax in e2 is confusing, also wiring is. Beginners think the inputs and outputs in ZCPU are normal numbers (some outputs are; like `Error`). You don't know if the input is actually a number or a highspeed port.
In my opinion there should be a `Highspeed` type to really make a difference between numbers, e2's wirelink and the actual highspeed.

**Comment by TomyLobo** [comment]
> Yeah, that's how you access a lot of High Speed entities by wirelink, just accessing them as if they were an array.

In fact, all of them. if you know one that doesn't work, that's probably a bug.

> To be honest, accessing High Speed wirelink should never have been by array. People should have been forced to use helper functions instead like `write()` or `read()`.

You don't access them "by array". You access them via the index operator, just *like* you'd access an array. It's just syntactic sugar.

**Comment by TomyLobo** [comment]
@suunrider ZCPU should be switched to wirelink, that's all.
Accessing complex objects via a "number" is just plain wrong.

**Comment by oldmud0** [comment]
Let's not get cynical now, shall we?

**Comment by TomyLobo** [comment]
cynical? are you sure you're using the right word?

**Comment by PhoenixBlack** [comment]
Highspeed link was always intended to be accessed as a virtual array (even ZCPU accesses it by same way it accesses arrays), with read/write operations implied by array read/array write.

**Comment by AbigailBuccaneer** [comment]
Tested, working.

Given the prominence of `wirelink` types, I'm now more convinced that entities shouldn't be able to modify input arrays to modify the internal array of an entity that's outputting it. So merging both `@rawinputs` and this (which existed to make DHDD work properly in the face of `@rawinputs`) was a mistake.

**Pull request merged**
