### PR TITLE
Fix for data plug/socket weld.

### PR DESCRIPTION
**Pull request by Cherser-s**
Fixed data plug welding to the socket while being held by the player. Also added sliders to the data plug tool for weld force limit and attach range.

### CODE REVIEW

**Comment by Divran** [comment]
is this just a copy paste from the other socket tool? lel

**Comment by Cherser-s** [comment]
lol partially

**Comment by EgrOnWire** [comment]
@Divran then why wasnt it implimented in the first place 😕

**Comment by Divran** [comment]
cos the datasocket is part of cpu/gpu and I didn't want to touch those

**Comment by Cherser-s** [comment]
lulz maybe make base class for plug/socket then.

**Comment by Divran** [comment]
hmm wouldn't it be better to use one of the existing files as a base class instead of making a completely new file

**Comment by Cherser-s** [comment]
hm nope because normal plug and socket create its own inputs/outputs.
Btw base classes are done.

**Comment by Divran** [comment]
nah there's no need to have a base class for these. I've experimented a bit but I've not got it working fully yet, but I know it's possible.

**Comment by Cherser-s** [comment]
I don't think it is possible to make this structure clean, because they don't have the same wire inputs and outputs, also wire socket/plug has methods which can't be overriden by data socket/plug

**Comment by Divran** [comment]
I just finished it. All I need now is someone with knowledge of cpu to test it.

**Comment by Cherser-s** [comment]
Also wire socket needs more arguements to set up. Look at the code.

**Comment by Divran** [comment]
See https://github.com/wiremod/wire/commit/a107474f68c540933e5cc5a8857b8585f9aafcfa

**Comment by Cherser-s** [comment]
oh, ok
Also need to check if plug will connect to the socket automatically after placing duplication. Pls check, I had fixes for it btw.

**Comment by Divran** [comment]
I didn't check that, but it should work since it works for the normal plug and all of that code is inherited from there

**Comment by Cherser-s** [comment]
As I expected. After duplication plug doesn't show as being attached to the socket. So it's need to be detached and attached again.

**Comment by Divran** [comment]
I will look at this tomorrow

**Comment by Divran** [comment]
Fixed it

**Pull request closed without merging**
