### PR TITLE
Fix #3082

### LINKED ISSUE #3082: rangerWhitelist(1) - use new 'whitelist' trace property
When I added this back in https://github.com/wiremod/wire/pull/1985, there wasn't really a good way of implementing it, but now as of [garrysmod.main/x86-64#9e093b](https://commits.facepunch.com/482895), traces now have a `whitelist` property that's 1:1 with how this _should_ have been implemented in the beginning.  Now that it can be improved, it should be.

Tag this with "enhancement" or whatever, I'm just opening an issue so I get off my ass and fix it later.

### PR DESCRIPTION
**Pull request by Fasteroid**

### CODE REVIEW

**Comment by Fasteroid** [comment]
tested on singleplayer, should be ready to go.

**Comment by Fasteroid** [comment]
I mean now it's ready

**Review by thegrb93 — APPROVED** [review]

**Review by thegrb93 — APPROVED** [review]

**Comment by Fasteroid** [comment]
actually ready now

**Comment by deltamolfar** [comment]
Fix that empty else statement >:(

**Pull request merged**
