### PR TITLE
add rangerWhitelist( true/false )

### PR DESCRIPTION
**Pull request by Fasteroid**
Added rangerWhitelist( `true` or `false` )

Default is false, rangerFilter() is a blacklist of entities the trace can't hit.
true "inverts" rangerFilter(), making it a whitelist of entities the trace can hit.

### CODE REVIEW

**Comment by thegrb93** [comment]
I don't think this will work for certain traceHulls.

**Comment by thegrb93** [comment]
Looks good to me though. We can do something special for trace hulls if the problem crops up.

**Comment by thegrb93** [comment]
Ah ents.FindAlongRay can input a hull. Make sure to do that for hull traces, @Fasteroid

**Comment by Fasteroid** [comment]
how's that look?

**Comment by thegrb93** [comment]
One last thing is we should make traces that use whitelist use like 3x more ops or something.

**Comment by Fasteroid** [comment]
+2 ops per each entity filtered
+2 ops per each entity 'anti'-filtered

**Comment by thegrb93** [comment]
This should be more efficient
```lua
tracedat.filter = {}
local foundEnts = ents.FindAlongRay( tracedat.start , tracedat.endpos, tracedat.mins, tracedat.maxs ) 
-- set real filter to everything we MIGHT hit for now

self.prf = self.prf + #tracedat.filter*2 -- add 2 ops for every potential entity hit, tells how expensive the find was

for _,found in ipairs(foundEnts) do
	for _,ent in ipairs(inputfilter) do
		if ent==found then
			goto ::nextEnt::
		end
	end
	tracedat.filter[#tracedat.filter + 1] = found
	::nextEnt::
end
```

**Comment by Divran** [comment]
Why use goto instead of continue?

**Comment by thegrb93** [comment]
continue would've continued the inner loop, but we want to continue the outer loop.

**Comment by Fasteroid** [comment]
> Why use goto instead of continue?

goto is also apparently against the style guide now :P

**Pull request merged**
