### PR TITLE
Rewrote netstream

### PR DESCRIPTION
**Pull request by thegrb93**
The ABI is the same so shouldn't see any conflicts with other mods.

### CODE REVIEW

**Comment by Denneisk** [comment]
And you wonder why I wanted built-in version control for netstream :P

**Comment by Denneisk** [comment]
Perhaps it would have been better to make sure the Starfall PR went through before starting these.

**Comment by thegrb93** [comment]
Need a review

**Comment by thegrb93** [comment]
I haven't seen any complains from it being merged in other addons so going to get it in

**Comment by Denneisk** [comment]
I was expecting you'd do that anyway.

**Pull request merged**
