### PR TITLE
Fix CPU/GPU/SPU errors caused by null entity

### LINKED ISSUE #1994: Timer error when deleting gpu
```
[ERROR] addons/wire/lua/entities/gmod_wire_gpu/init.lua:83: attempt to index field 'Cache' (a nil value)
  1. unknown - addons/wire/lua/entities/gmod_wire_gpu/init.lua:83

Timer Failed! [wire_gpu_resendtimer_929016][@addons/wire/lua/entities/gmod_wire_gpu/init.lua (line 81)]
```

### PR DESCRIPTION
**Pull request by nicothegoat**
Fixes #1994.

Fixes errors caused by a CPU/GPU/SPU being deleted before its queued upload/cache resend/model reset/sound source init happens.

### CODE REVIEW

**Comment by thegrb93** [comment]
This looks good at first glance. I'd like to look a bit closer and make sure there's not supposed to be some cleanup that needs to happen.

**Comment by thegrb93** [comment]
I think it should be fine. Could you change those disgusting timer.Create to timer.Simple though?

**Comment by nicothegoat** [comment]
Done.

**Review by thegrb93 — APPROVED** [review]

**Comment by thegrb93** [comment]
Thanks!

**Pull request merged**
