### PR TITLE
fix #2940

### LINKED ISSUE #2940: E2 :wirelink() broken backwards-compat
Using :wirelink() on an entity that doesn't have one by default now returns an invalid wirelink.
Seems to have been broken by #2891 since `entity:wirelink()` no longer creates a wirelink.

Before: https://github.com/wiremod/wire/blob/4edf127222e5c584883739abdc3f4cef55f13117/lua/entities/gmod_wire_expression2/core/custom/wiring.lua#L108-L116

After: https://github.com/wiremod/wire/blob/95adeb437e8c1ac1f5ac13c83a23cd303d386ed8/lua/entities/gmod_wire_expression2/core/custom/wiring.lua#L108-L116

Probably easy to fix if this tiny change is reverted.

### PR DESCRIPTION
**Pull request by Fasteroid**

### CODE REVIEW

**Comment by Fasteroid** [comment]
see #2942

**Comment by Fasteroid** [comment]
@Vurv78

**Comment by Fasteroid** [comment]
> I'm sorry, is your code structured so you use `createWire` to use dynamically generated wirelinks? Is that the problem here?

I'm using the return value of `CamController:wirelink()` and assuming it's a valid wirelink (which it was before this PR)


[wrecking_ball/modules/seatcontrol_module.txt](https://github.com/Fasteroid/expression2-public/blob/e1f31768e5437a3eee5bcaf1fc5528395ba20fbb/wrecking_ball/modules/seatcontrol_module.txt#L16C1-L21C6)
```golo
    function seatrotation_setupCamController(CamController:entity){
        CamController:linkTo(SEATROTATION_Seat)
        SEATROTATION_CamLink = CamController:wirelink()
        SEATROTATION_CamLink["Position",vector] = SEATROTATION_HampterEyePos
        SEATROTATION_CamLink["Parent",entity]   = SEATROTATION_Seat
    }
```
When I do this now, I get back a bugged wirelink that doesn't do anything when I write to its inputs.

**Comment by Denneisk** [comment]
If #2942 takes too long to merge then I'll merge this.

**Review by Denneisk — APPROVED** [review]
If #2942 doesn't get merged within a day then I'll merge this since it's a pretty big problem.

**Pull request closed without merging**
