### PR TITLE
Remove C operators from filebrowser/soundbrowser

### PR DESCRIPTION
**Pull request by shadow7483147**
// /**/ comments
if (condition) then parenthesis
!Call inversions

This is a very blind pick-and-replace commit so I didn't change anything such as continues or other code structure. But it does work. And that's fair enough.

### CODE REVIEW

**Comment by shadow7483147** [comment]
These types of C operators still exist in lua/wire/gpulib.lua, timedpairs.lua, lua/wire/client/wire_listeditor.lua, wire_soundpropertylist.lua, lua/wire/stools/clutch.lua, emarker.lua, fx_emitter.lua, latch.lua, soundemitter.lua, spawner.lua, and waypoint.lua.
All just from searching "//" in the entire project.

**Comment by Divran** [comment]
keeping continue is fine. shouldve been in lua to begin with anyway

**Comment by shadow7483147** [comment]
Several if conditions are made up of `if (Comp1 > Comp2) and (Comp3 == 1) or (Original) then`, would it be wise to omit these parenthesis or shall I leave them alone?

**Comment by thegrb93** [comment]
Doesn't really matter as long as the logic stays the same and it's not less readable

**Comment by shadow7483147** [comment]
A bunch of the E2 extensions use
> /*********************************\
> \*********************************/
as block comments. Should these be removed as well?

**Comment by thegrb93** [comment]
Don't restyle the whole codebase pls

**Comment by shadow7483147** [comment]
https://github.com/shadow7483147/wire/commits/how-bout-i-do-anyway

**Pull request merged**
