### PR TITLE
Improve luacheck accuracy by moving the Expression 2 base components into E2Lib and adding some E2 globals to luacheckrc

### PR DESCRIPTION
**Pull request by TomyLobo**

### CODE REVIEW

**Comment by TomyLobo** [comment]
@Divran @Nebual @AbigailBuccaneer any ramifications?

**Comment by adosikas** [comment]
If you want to find some more globals, you can just run luacheck and scan the output for relevant warnings

From wire folder run: `luacheck lua <additional parameters> | grep -o 'global variable.*' | sed -e 's/^global variable \(.*\)$/\1/' | sort | uniq`

**Comment by TomyLobo** [comment]
or shorter: `luacheck lua <additional parameters> | sed -nr 's/^.*global variable (.*)$/\1/' | sort -u`

**Comment by TomyLobo** [comment]
rebased onto current master

@AbigailBuccaneer if you think it's good and think your review was thorough enough, merge it :)

**Comment by Divran** [comment]
@AbigailBuccaneer @TomyLobo why hasn't this been merged yet

**Comment by adosikas** [comment]
This commit breaks E2, as some places are not updated, like inside RunString here:
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/base/compiler.lua#L654

**Comment by TomyLobo** [comment]
oops, nice spot

**Comment by TomyLobo** [comment]
hnng, @Divran could you stop using "squash" already?

**Comment by Divran** [comment]
@TomyLobo but you told me to use squash
also I didn't merge this

**Comment by TomyLobo** [comment]
oh, right, you didn't, my bad.

but, no I didn't tell you to squash this PR.
...or any PR in the last 2 years or something.

I changed my mind on the subject a *while* ago.
What needs to happen is that if the history we're handed is messy, we need to ask the author to clean it up before we merge.

**Pull request merged**
