### PR TITLE
Clean up wire_expression2_unlimited logic

### LINKED ISSUE #1238: Replace e2quota timer with cvar callback
[`gmod_wire_expression2/init.lua`](https://github.com/wiremod/wire/blob/98ae4f1eb66fd91a60c06358103b6c9e43258a63/lua/entities/gmod_wire_expression2/init.lua#L18) contains a repeating timer named `"e2quota"` that could be implemented in terms of a call to [`cvars.AddChangeCallback`](http://wiki.garrysmod.com/page/cvars/AddChangeCallback) instead.

### PR DESCRIPTION
**Pull request by AbigailBuccaneer**
Fixes #1238.

### CODE REVIEW

**Comment by Divran** [comment]
Don't you need to add callbacks for hardquota, softquota and tickquota here as well?

**Comment by AbigailBuccaneer** [comment]
I don't know why I even bother writing code when I'm so sleep-deprived.

**Comment by AbigailBuccaneer** [comment]
@Divran fixed. Good to merge?

**Comment by Divran** [comment]
looks good

**Pull request merged**
