### PR TITLE
Create ability to lock players inside of vehicles.

### PR DESCRIPTION
**Pull request by thegrb93**
Useful if you want to make your own nova prospect. Defaults to disabled.

### CODE REVIEW

**Comment by oldmud0** [comment]
No, just because GMod Lua lets us do it doesn't mean that we should. This could be used for malicious purposes. (ex. you get locked in a seat by a criminal in RP)

**Comment by thegrb93** [comment]
Then leave wire_pod_allowlockinsidevehicle 0 where it is default.

**Comment by Divran** [comment]
I'm hesitant about this. What does everyone else think? @AbigailBuccaneer @Nebual @Jack37

**Comment by arduinium** [comment]
Add prop protection check so that only friends can be locked

**Comment by Jack37** [comment]
It's useful and disabled by default so I guess it can be added.

**Comment by AbigailBuccaneer** [comment]
As it's disabled by default, I'd say this is sensible. A prop protection check wouldn't be a bad thing, but checking friends isn't particularly flexible or prop-protection-system-agnostic. It may be possible to call the `CanTool` hook on another player dummytrace using the wire pod tool name, and I think that'd be a nice thing to have in the future.

But I think this is fine as it is - if the server admin's enabled it, and the server's prop protection settings let you use a vehicle to enter it in the first place, then you shouldn't expect bad things not to happen.

**Comment by Divran** [comment]
Ok then it's fine by me. @AbigailBuccaneer you go ahead and merge when ready

**Pull request merged**
