### PR TITLE
Use strings to network value in Screens

### LINKED ISSUE #2760: Wire-Screens inaccurate with decimal numbers when all settings are disabled
**Describe the bug**
WireMod screens showing inaccurate values when Text-Screens show normally

**To Reproduce**
1. Spawn Screen with all settings off except "Only one value" turn that on
2. Create Constant Value with a number with decimals. I used: 427.3716829
3. Spawn Constant Value
4. Wire Screen to Constant Value
5. See horribly inaccurate data on screen

**Expected behavior**
Screen should just output what was wired in when all format settings are off.
As u can see it displays perfectly on the Text-Screen when Wired to a "Number to String" gate

**Screenshots**
image

image
image

### PR DESCRIPTION
**Pull request by Denneisk**
Fixes #2760 

Not my ideal solution since obviously it's a string instead of a number, but unless anyone knows how to encode a double in a smaller format, this will have to do.

### CODE REVIEW

**Comment by thegrb93** [comment]
DT vars should work fine. We can even use the on change callback to let the screen know to rerender

**Comment by Denneisk** [comment]
I feel like it'd be a waste of a network string just for this very specific task. I'd see that more as something delegated to a library.

**Comment by Divran** [comment]
why cant you just use a text screen for the rare cases where you absolutely need to display a number to 7 decimal points for some reason

**Comment by thegrb93** [comment]
> I feel like it'd be a waste of a network string just for this very specific task. I'd see that more as something delegated to a library.

Wdym a waste. The limit is per entity

**Comment by Vurv78** [comment]
> > I feel like it'd be a waste of a network string just for this very specific task. I'd see that more as something delegated to a library.
> 
> Wdym a waste. The limit is per entity

Think he meant to using the net library instead. Just really don't like the idea of networking a string for this, massive waste of bandwidth :\

> why cant you just use a text screen for the rare cases where you absolutely need to display a number to 7 decimal points for some reason
> 
> Or you can just multiply the number up a couple orders of magnitude before displaying it

Agree w/ this since we don't have a proper nwvar double solution

**Review by thegrb93 — APPROVED** [review]
Would be nice if the values were only rendered to the GPU when they are changed since DTVars support callbacks for when they are changed. I think the RenderToGPU and Render functions can do that. Maybe can be done in via a new issue

**Pull request merged**
