### PR TITLE
Added E:use()

### PR DESCRIPTION
**Pull request by ajloveslily14**
made a new pull because the old one was a mess

### CODE REVIEW

**Comment by adosikas** [comment]
( Replaces #1472 ) Reposting my comment:

> Naming it propUse would be kinda weird, since this wouldn't be used on props.
> `deparent` and `parentTo` don't have the prop prefix either, despite being in propcore.
> 
> Also it would make sense to add a exception so world props can be used by anyone.

**Comment by CaptainPRICE** [comment]
I'm fine with this being in E2 prop-core.
But, do add the proposed `runOnUse` and ConVars.. (see #1399).
(...I'm wondering why I didn't push my own branch... 🤔)

**Comment by Divran** [comment]
>But, do add the proposed runOnUse

why does everyone seem to want a feature that already exists? I've seen at least 3 people on discord who want this, even though runOnKeys is already a thing. In addition, runOnKeys is better in every way because it allows you to enable use on things that aren't physical entities, such as holograms or egp emitters. Instead of adding runOnUse, we should upgrade runOnKeys with the filter we've talked about so that you can specify which keys should trigger your E2 (thus giving you less ops usage).

**Comment by Divran** [comment]
Alright so I'll merge this as long as the answer to this question is correct

Does this properly get detected by prop protection mods? We need to make sure you can't use this to bypass prop protection.

In addition to this, I normally don't give a shit about darkrp, but if we're making sure that we're not bypassing prop protection then someone could boot up a darkrp server real quick and make sure that the same check darkrp has to block wire users from abusing money printers will work for this, so that you can't just run `E:use()` on everyone's printers every tick and steal everyone's money. And also every single dropped pile of money the instant they are dropped. Because I have some memory of printers and money piles not being owned by anyone, so normal prop protection checks might not work for them.

**Comment by Divran** [comment]
Also, note that the wire user works differently.

https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_user.lua#L38-L44
```Lua
		if not hook.Run( "PlayerUse", ply, trace.Entity ) then return false end

		if trace.Entity.Use then
			trace.Entity:Use(ply,ply,USE_ON,0)
		else
			trace.Entity:Fire("use","1",0)
		end
```

it first runs a hook, most definitely for prop protection's benefit, and then after that it checks if the entity has a use function specified. If not, it runs the code that you have in this PR. I'm not actually sure if this check & calling of `Ent:Use` is necessary, just pointing out that this is the way the wire user works.

**Comment by ajloveslily14** [comment]
It uses the same check as propBreak() does so I assume that it doesn't bypass it I havnt tested though

**Pull request closed without merging**
