### PR TITLE
E2: Add "steamIDFrom64" and "steamIDTo64" functions

### PR DESCRIPTION
**Pull request by CaptainPRICE**
This pull request (after merged) would add the following to Expression 2 gate:

new Functions:

Signature | Description
------------ | -------------
string=steamIDFrom64(string) | Converts Steam Community ID to Steam ID
string=steamIDTo64(string) | Converts Steam ID to Steam Community ID

### CODE REVIEW

**Comment by TomyLobo** [comment]
What happens if i enter an invalid id?

**Comment by CaptainPRICE** [comment]
@TomyLobo If you enter an invalid ID, then the function returns an empty string (it is like directly aliasing the game function) or whatever the underlying engine code in lua_shared returns (will always be a string). Pretty simple and very straightforward.
See [this](https://wiki.garrysmod.com/page/util/SteamIDFrom64) and [this](https://wiki.garrysmod.com/page/util/SteamIDTo64) wiki/docs page.

**Comment by TomyLobo** [comment]
As long as it doesn't throw errors, it's ok.
E2 has no mechanism of catching errors, and I don't think we should add one.
Errors should be considered bugs in the framework.

**Comment by CaptainPRICE** [comment]
@TomyLobo @Divran Why is this still not merged, yet?
It is safe (doesn't throw errors).
(Please merge, I don't want to mess up my branches again :panda_face:)

**Comment by Divran** [comment]
This is in its own file called "steamidconv.lua". Pretty sure this new file would need to be added to the bottom of the list here https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/extloader.lua#L177 or it won't run

**Comment by Jack37** [comment]
Maybe we could rename unitconv.lua to conv.lua or something more general and add this to it? Then we can have one file with unit conversion section and steam ID conversion section for the sake of file count.

**Comment by bigdogmat** [comment]
Just noticed, why localize util if you're already localizing the functions

**Comment by bigdogmat** [comment]
Ok I'm really confused, @CaptainPRICE did you get any errors after this being merged?

I'm getting this

```
[ERROR] entities/gmod_wire_expression2/core/steamidconv.lua:1: '=' expected near 'util'
  1. unknown - entities/gmod_wire_expression2/core/steamidconv.lua:0
```

Even though that line is valid, I went into my editor and retyped it and the error went away. Everyone else I know who updates from git is also getting the error.

**Comment by bigdogmat** [comment]
Ok, yeah, looked into the byte sequence for the file and it starts with 239, 187 and 191 which is the uft8 byte order mark.

**Comment by CaptainPRICE** [comment]
Ah. Wrong file encoding? (Ouch, but not kinda my fault, UTF-8 should work right, but UTF-8 with BOM doesn't, so I blame this on Garry)

**Comment by AbigailBuccaneer** [comment]
Ouch. This is the kind of thing that I'd like to see checked automatically.

(FWIW, UTF-8 with BOM is mostly nonsense, and there's basically no benefits to using it: https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8 )

**Comment by oldmud0** [comment]
Some M$ nonsense like Office and Visual Studio still require BOM to recognize files. It's really stupid.

**Comment by CaptainPRICE** [comment]
> Visual Studio still require BOM to recognize files

Not really required. It just defaults to UTF-8 with BOM when creating a new file, but of course there's a public extension to "fix" this ([here](https://vlasovstudio.com/fix-file-encoding/)).

**Comment by TomyLobo** [comment]
UTF-8 BOM was never really required by anything.
On the contrary, UTF-8 is designed in a way to allow autodetection without a BOM.

**Pull request merged**
