### PR TITLE
Reworked E2 extensions loading + changed a few other things

### PR DESCRIPTION
**Pull request by arduinium**
- Fixed issue with loading of inexistent or renamed extensions.
- Improved listing of extensions, now shows a pleasant table.
- Made sure the extensions names are always lowercase.
- Added hooks "Expression2_PreLoadExtensions" and
"Expression2_PostLoadExtensions", for use in external scripts.
- Added automatic reload timer (10 seconds) after changing an extension
status by commands.
- Added command 'wire_expression2_extensions' so players can see
available extensions on server.

This should be bullet proof, yet if you find any bug then please tell me

### CODE REVIEW

**Comment by arduinium** [comment]
The list look like this when printed:
```
 +---------------------------------+
 |          E2 EXTENSIONS          |
 +----------------+----------------+
 |    ENABLED     |    DISABLED    |
 +----------------+----------------+
 | camera         | constraintcore |
 | console        | effects        |
 | file           | holoanim       |
 | find           | joystick       |
 | glon           | misc           |
 | holo           | remoteupload   |
 | http           | tracesystem    |
 | light          |                |
 | npc            |                |
 | propcore       |                |
 | ranger         |                |
 | sound          |                |
 | wiring         |                |
 +----------------+----------------+
```
Good, no?

**Comment by Nebual** [comment]
Haven't tested, but changes look good! Nice table.

**Comment by arduinium** [comment]
No more changes planned, you can merge. Unless you have something against it?

**Comment by Divran** [comment]
So should we merge this? I haven't tested it. Should someone test it first?

**Comment by arduinium** [comment]
This was tested carefully and I couldn't find any bug, but feel free to test too

**Comment by TomyLobo** [comment]
So this wasn't even tested by anyone but @arduinium? 68 additions and 39 deletions, i.e. a rewrite, and noone tests it?

**Pull request merged**
