### PR TITLE
Fix "\\" breaking syntax highlighter when offscreen

### LINKED ISSUE #890: E2 incorrect highlighting of multi-line strings
Enter the following code in the E2 editor:

```
"\\"
test
```

and then scroll so that `"\\"` is off-screen, but `test` is visible (you can add blank lines to the end to enable scrolling). `test` will be highlighted as a multi-line string (grey), when it's not one. This is because EDITOR:ResetTokenizer sees `\"` as an escaped `"` (which doesn't end the string), without taking into account that the `\` is itself escaped.

The fundamental problem here is that code has to be duplicated between ResetTokenizer and SyntaxColorLine to detect multi-line structures correctly. A possible solution is to remember the state of `self.multilinestring` and `self.blockcomment` at the start of each line, and then reset them to the saved values, instead of attempting to recompute them with duplicated code.

(Of course, another possible solution is to make ResetTokenizer detect escapes in strings properly, but that makes the syntax highlighting system even less understandable, instead of more)

### PR DESCRIPTION
**Pull request by adosikas**
Fixes #890 

When encountering a " during a string, count the \ before to make sure " isn't the thing that is escaped

Also improve performance by not checking before/after if not required

### CODE REVIEW

**Comment by TomyLobo** [comment]
I love the fact that you made good use of luacheck

**Comment by TomyLobo** [comment]
I created #1323 in order to remove the remaining issues travis is reporting for your PR

**Comment by adosikas** [comment]
Rebased this pull without the changes to code style, as it doesn't look like luacheck has been fixed.

**Comment by Divran** [comment]
@AbigailBuccaneer @TomyLobo merge this?

**Comment by TomyLobo** [comment]
@Divran I havent reviewed this. This isn't my code anyway. Looks like you and @Grocel wrote it.

**Comment by Divran** [comment]
@TomyLobo yes, I just asked because you had left a comment on this issue before. So I'll merge this after you answer this question: to squash or not to squash? You've told me to use it before but in a different issue recently you left a contradicting message

**Comment by Grocel** [comment]
@TomyLobo This is not my code. I never made changes to the text editor beside that sound browser button years ago.

**Comment by TomyLobo** [comment]
never use the github-integrated squash or rebase feature, unless you have a good reason to.
Sure, it may leave a linear history, but all context is lost.
For instance, if change A and B happen at the same time, you "rebase/squash and merge" A and then B, no information about the fact that they were once siblings is retained.
This is critical if there's some kind of overhaul in A that would actually require a change in new code from B.

**Comment by Grocel** [comment]
Jesus, that are some pre-GitHub changes. These are a patch I made and put in a thread in the forum to fix some some minor issues affecting the old sound browser, the unit conversion system and the version detection. My statement above about the editor still applies. I guess Divran added his changes as the applied the patch on his side.

**Pull request merged**
