### PR TITLE
E2: Fix E:children()

### PR DESCRIPTION
**Pull request by TwistedTail**
Fixed function not returning an array as intended.

### CODE REVIEW

**Comment by bigdogmat** [comment]
Are there instances where `GetChildren` returns something that's not a table?

**Comment by TwistedTail** [comment]
No as far as I know, which makes it really really weird, especially since the function was really simple yet it's returning an empty array instead of an array with the children entities.

**Comment by bigdogmat** [comment]
What you've turned it into is exactly equivalent to what it was. Unless `GetChildren` was returning a non sequential table, which afaik it does not.

**Comment by TwistedTail** [comment]
Logically, it's the same. But for some reason they're acting differently.

```
@inputs E:entity

print(E:children())
print(E:getChildren())

[table]	
[Entity [107][prop_physics]]
```

This is the code I'm testing, children being the function we already have and getChildren being the function with my code. E is just a fridge with another fridge parented to it.

**Comment by bigdogmat** [comment]
That behavior in `print` should only occur if the table isn't sequential, could you use `printTable` instead and post the output.

**Comment by TwistedTail** [comment]
Yeah, it's showing the table with the children
`Entity [366][prop_physics]	=	Entity [366][prop_physics]`

**Comment by bigdogmat** [comment]
That's strange, after testing that seems to be the behavior. Other than the styling issues this pr should be reopened.

**Comment by Divran** [comment]
ah yes garry's style of "i'll make both the keys and the values be the values! genius!". There's other functions that do this retarded shit too

**Comment by bigdogmat** [comment]
> EDIT: the only styling issues I can see is that this pr uses 4 spaces instead of tabs

Space after comma in loop

**Comment by TwistedTail** [comment]
There, corrected all the mentioned styling issues.

**Pull request merged**
