### PR TITLE
added hook call to validMaterial

### PR DESCRIPTION
**Pull request by Divran**

### CODE REVIEW

**Comment by Divran** [comment]
@CaptainPRICE please review and test this PR. I have written it outside of gmod without testing it. If your tests are successful then I will merge it.

**Comment by thegrb93** [comment]
This is really unnecessary. Why not just add the shader he's bitching about being blocked to the whitelist.

**Comment by Divran** [comment]
could also do that, but wasn't there another issue about that material being abusable?

**Comment by thegrb93** [comment]
Seems safe to me. Yeah you can put a prop over someone with it and blind them, but the same can be said for any hologram.

**Comment by thegrb93** [comment]
I'll probably disable it on my server though because it allows players to be invisible while killing other players.

**Comment by Divran** [comment]
holograms can be hidden with a clientside hologram, props can't

**Comment by Divran** [comment]
Closed by #1439

**Comment by Divran** [comment]
I'm deleting the branch now to avoid cluttering up the repo, but since this code is so small, here's the entire code in case we want to bring it back in the future (we probably won't but saving this in this form doesn't hurt)
```Lua
 local function validMaterial(material)
 	-- pp/copy is always blocked
  	if string.find(string.lower(material) , "pp[%./\\]+copy" ) then return "" end
 	-- call a hook to see if any other mods/scripts would like to change the behavior of this check
 	local hookret = hook.Run( "e2lib_validmaterial", material )
 	if hookret == nil then -- if the hook returns nil, proceed as usual
 		local m = Material(material)
 		if m then
 			local s = m:GetShader()
 			if s == "VertexLitGeneric" or s == "UnlitGeneric" or s == "Refract_DX90" then
 				return material
 			end
  		end
 	elseif isbool(hookret) then -- if the hook returns true or false, allow or block respectively
 		return hookret and material or ""
 	elseif isstring(hookret) then -- if the hook returns a string, set material to that
 		return hookret
  	end
  	return ""
  end
```

**Pull request closed without merging**
