### PR TITLE
Remove the per-category limits on gates

### PR DESCRIPTION
**Pull request by immibis**
Because why do they exist?

This does remove the ability to easily disable, say, entity gates only. However, server owners can get the same effect by deleting lua/wire/gates/entity.lua. I'm not sure if that's an acceptable solution; if not, I'll add a convar to disable specific categories. (a per-category *limit* is still silly)

### CODE REVIEW

**Comment by Nebual** [comment]
Limits are in general a pretty silly way of accomplishing control, especially these limits. Yank em!

**Comment by Divran** [comment]
:+1:

**Comment by AbigailBuccaneer** [comment]
Does this still enforce a per-player limit on all gates? If so, LGTM.

**Comment by immibis** [comment]
Yes, this adds `sbox_maxwire_gates`.



Side-thought: I wonder if it would make sense (not for this PR) to revamp how limits work entirely. Wiremod has over 100 of them, and it's silly that if I, say, run into my explosives limit, then I can still make several more *simple* explosives. Or if I hit my thrusters limit, I can make some vector thrusters and wire them to only work along one axis. Or I hit my buttons limit, and start using levers. Data ports and address busses and extended busses have separate limits, even though (from a user point of view) they're just like gates.

**Comment by AbigailBuccaneer** [comment]
I'm going to merge this soon-ish unless anybody objects. Thanks again @immibis!

**Comment by BoggLog** [comment]
@immibis are you playing gmod yourself? I'm not against this, but there may really be some applicable situations. For example, roleplay servers. They usually disable wire at all, because they are just too lazy to restrict all needed to be restricted (like you don't want somebody to use money finder, and many other cases). But some keep wiremod, just restricting e2, allowing to use cpu and gates. And here is when these limits come useful: you don't want somebody to use beacon sensor, target finder, and some other gates which were made later, duplicating e2 functions, like find() and maybe some others.
Same for some other gamemodes, like survival ones, probably flood and others. I would better leave them.

**Comment by AbigailBuccaneer** [comment]
@BoggLog you've misread the pull request - currently, there are separate limits for logic gates and numeric gates etc., and now gates are just one category. This doesn't merge all wire entity limits into one, just gates.

**Comment by Divran** [comment]
The beacon sensor and target finder are not gates

**Comment by BoggLog** [comment]
@Divran Oh, okay xD Didn't use for too long. But I'm sure there are some gates capable to do the same.

**Comment by immibis** [comment]
@BoggLog I already suggested a workaround - just delete those files from Wiremod. Each gate category is in its own file, and they're dynamically loaded.

Then I asked if anyone wanted a toggle for each category as a replacement, and nobody responded.

**Comment by immibis** [comment]
@BoggLog By the way, not all entity gates are equal. A typical server owner might want to keep "owner" and "entity equal" gates, but remove "apply force" gates.

(Although in practice, almost all server owners don't recognize the amount of power gates have, and think they're fine as long as they ban E2)

**Comment by BoggLog** [comment]
@immibis True. Well, maybe it's not a problem then. Just the only difference would be that owner will have to look into wire files instead of just using config/console/admin mod's gui.

Hm, and what if someone is running a server with changing gamemodes wanting to disable some gates for one of them, but keep them for others, can he?

**Comment by AbigailBuccaneer** [comment]
A toggle for each category would be ideal @immibis - I hadn't considered the use case of different game modes wanting only some of the gates, and I don't think server owners should have to delete files from Wiremod in order to control its operation.

**Comment by immibis** [comment]
@AbigailBuccaneer What about the case where a server owner wants to remove some of the gates from a category? ("apply force" etc, but not "owner" or "entity equals")

**Comment by immibis** [comment]
Also, since the old default limit was 30 gates *per category*, should I change the default limit to 60 or 90 gates to make up for it?

**Comment by AbigailBuccaneer** [comment]
@immibis they wouldn't be able to remove individual gates under the old system, so I'm happy to not support it in the new system. And yes, as somebody who used to enjoy using gates for things that others would use E2 for, 30 gates is not enough.

**Comment by BoggLog** [comment]
@AbigailBuccaneer agree. I think it's good to have about 100 limit overall, but maybe not for game engine-related ones, like find... It's not a problem having 100 add gates, but not find... Ideally it would be a limit for every single gate and 100 for all

**Comment by Divran** [comment]
We could make our own limit system just for gates. Each gate could have
different "costs", so for example find gates and applyforce gates cost
5-10, while add gates and such cost 1.

**Comment by BoggLog** [comment]
@Divran sounds good, but does the work worth it? And if you will have 10k limit so you can place 100 find gates this might turn out not so good, if I'm right.

**Comment by immibis** [comment]
There aren't any find gates; that's what the target finder is for (which is not a gate).

**Comment by Divran** [comment]
@immibis oh right. applyForce gates exist, though

**Comment by immibis** [comment]
@AbigailBuccaneer @BoggLog updated.

100 entities seems like quite a few, but players who want to spam entities can already do that just by abusing the fact that each tool has its own limit (say, 30 target finders + 30 beacon sensors + 30 vector thrusters + 10 normal thrusters)

**Comment by immibis** [comment]
Fixed (and rebased, so the history is clean).

**Comment by oldmud0** [comment]
oh come on, it won't break your computer :angry:

**Comment by BoggLog** [comment]
Neat. Thanks, @immibis

**Comment by AbigailBuccaneer** [comment]
Anyway, unless anybody has any objections I'll merge this. Thanks @immibis :)

**Pull request merged**
