### PR TITLE
E2 Pickup events

### PR DESCRIPTION
**Pull request by Astralcircle**
Events for tracking the pickup/drop of entities using the physgun, gravity gun, and hands.

### CODE REVIEW

**Comment by deltamolfar** [comment]
I think having just 2 event playerPickup and playerDrop + the source of pickup/drop in string var or whatever would be better, as it would allow for single place of logic.
Say I want to track if prop is being held/dropped by hands OR gravgun. Having to track that in 4 events, instead of 2 + simple if statement seems worse to me

**Comment by unknao** [comment]
Never have i wanted something so badly and not known about it.

**Comment by thegrb93** [comment]
Does the helper have events? Need to update helper if so

**Comment by deltamolfar** [comment]
Nope, it doesn't

**Review by thegrb93 — APPROVED** [review]

**Pull request merged**
