### PR TITLE
Don't accept unmatched string delimiters in HLZASM

### LINKED ISSUE #1011: HL-ZASM Strings
In HL-Zasm you can write strings like: ```"Text'```, ```'Text"``` or ```'Text'```. The character ```'``` isn't only used for characters in HL-Zasm. This behavior prevents to define a ```'``` in the string, however you can define it with ```\'```. In ANSI C you can define such strings: ```"Text: 'Text'"```.

### PR DESCRIPTION
**Pull request by AbigailBuccaneer**
Now `"Foo'` isn't a valid string constant, but `"isn't"` is.

Fixes #1011

### CODE REVIEW

**Comment by AbigailBuccaneer** [comment]
@suunrider would you be able to test this? I won't have a computer at my house until Saturday.

**Comment by suunrider** [comment]
The string ```"Foo'``` errors with ```Newline in string constant```, also the editor highlights it like a normal string.

**Comment by AbigailBuccaneer** [comment]
@suunrider okay, I've changed the error message for `"Foo'` and the editor should highlight it in red. (There seems to be no proper syntax error highlighting colour?)

**Comment by suunrider** [comment]
There aren't any syntax checks in the zcpu editor, so doesn't "notfound" color exists. Just add ```["notfound"] = { Color(240, 96, 96), false},``` to the colors (copied from e2).
The error messages work properly now :+1: .

**Comment by AbigailBuccaneer** [comment]
Whoops, I didn't realise the two syntax highlighters had their own syntax colour tables. Fixed.

**Comment by suunrider** [comment]
The error highlighting ain't working: ```"Foo``` gets highlighted as string

**Comment by AbigailBuccaneer** [comment]
Okay, I'll wait until I have a computer I can run and test my code on. Thanks for your help.

**Comment by immibis** [comment]
In most editors I've used `"foo` would be highlighted as a string. (I don't know the reason - maybe so they don't change colour when you finish typing them)

**Comment by immibis** [comment]
If it's meant to be like C then 'A' should be the number 65 (ASCII code of A) rather than a string.

**Comment by suunrider** [comment]
It already does that (see [hc_tokenizer.lua#L288](https://github.com/wiremod/wire/blob/master/lua/wire/client/hlzasm/hc_tokenizer.lua#L288)).

**Comment by suunrider** [comment]
Why did you change the C-Style operators to lua ones?

**Comment by AbigailBuccaneer** [comment]
Because my editor doesn't understand them, and those particular ones were causing it to show errors down the entire rest of the file, and we have a rule that the C-style operators shouldn't be used in our code. So I figured it'd be better to just sneak in that unrelated improvement to the codebase while I'm there :wink:

**Comment by suunrider** [comment]
Oh, some codestyle guidelines would be useful then since there are many different coding styles in wiremod

**Comment by AbigailBuccaneer** [comment]
#350 was the closest we got, but you're right that it would be worth having some documentation somewhere.

**Comment by suunrider** [comment]
Once ported the HL-ZASM Compiler out of gmod: https://github.com/suunrider/hlzasm. Uploaded it to github, i thought it maybe would be useful for you. I don't have a zcpu emulator yet, so it's only useful to check if something parses.

**Pull request merged**
