### PR TITLE
Update Workshop to Include recent changes

### PR DESCRIPTION
**Pull request by Scottyprogrammer**

### CODE REVIEW

**Comment by TomyLobo** [comment]
----
Everything above this comment is accumulated from all the PRs that are part of this :)

**Comment by Scottyprogrammer** [comment]
And by recent changes in the title I meant all the way back in May. ;)

**Comment by Scottyprogrammer** [comment]
Any news on this? The commits I made a while back are pointless if servers don't update. Not to say they couldn't use the svn, (too lazy?,) they just rely on workshop.

**Comment by Divran** [comment]
yeah let's go

**Comment by Scottyprogrammer** [comment]
Now that this was merged how do I go about actually getting it on the workshop?

**Comment by bigdogmat** [comment]
The workshop should auto update once the branch gets a new commit, that is unless it's broken again

**Comment by Scottyprogrammer** [comment]
I assume it wouldn't take more than a day, so I guess its broken. Workshop shows last update in March.

**Comment by oldmud0** [comment]
Hasn't it been broken for a long while now?

**Comment by bigdogmat** [comment]
> Hasn't it been broken for a long while now?

Worked the last time, although that was before all the compromised account

**Comment by TomyLobo** [comment]
So did this work or not?
If not, someone should tell @Anticept

**Comment by CaptainPRICE** [comment]
> So did this work or not?

Apparently not.

**Comment by TomyLobo** [comment]
Messages him on steam

**Comment by Anticept** [comment]
I don't yet have the password to the wiremod account.

**Comment by Anticept** [comment]
@wiremod/wiremod-core @wiremod/high-developers @wiremod/developers I now have access to the wireteam account. Let's get this stuff updated, get adv dupe 2 online, etc.

**Comment by Anticept** [comment]
I'm silly. This is not an issue, it's a pull request. Starting a new issue.

**Pull request merged**
