### PR TITLE
CPU Clk patch

### PR DESCRIPTION
**Pull request by immibis**
To summarize: This fixes cases where CPUs had to be turned off and on again after uploading new programs.

The CPU has a field "Clk" which normally mirrors its "Clk" input (which turns the CPU on or off). However, in some situations, other factors cause the CPU to turn on or off, by overwriting this field, so the CPU "forgets" the state of the input. For example, the CPU turns off if it encounters an error.

If a new program is uploaded after the CPU encounters an error, the CPU currently *stays* off, because it doesn't remember whether it was turned off by a wire input, or whether it encountered an error. The workaround is to turn it off and on again (via the wire input).

I've changed it so that the CPU separately remembers whether it's turned on by the wire input, and whether it's turned off because of an error. The error flag is reset when the CPU is reset, such as when a new program is uploaded.

I also changed it to a boolean, because it should be a boolean.

This PR also contains #998, because they touch the same code.

### CODE REVIEW

**Comment by immibis** [comment]
@suunrider Any opinion? You seem to use CPU, so you've probably encountered this bug.

**Comment by suunrider** [comment]
I can confirm this behavior, but didn't check if this fixes it yet.

**Comment by oldmud0** [comment]
Looks like CPU needs quirks mode.

**Comment by AbigailBuccaneer** [comment]
@PhoenixBlack unless you have any objections I'm gonna merge this soon-ish.

**Comment by AbigailBuccaneer** [comment]
Oh congrats on being #1000 by the way! :100:0

**Comment by immibis** [comment]
Drat, @AbigailBuccaneer's uncovered the real reason I was submitting so many pull requests!

JK.

**Pull request merged**
