### PR TITLE
Improve Luacheck accuracy

### PR DESCRIPTION
**Pull request by AbigailBuccaneer**
This pull request updates `.luacheckrc` to properly specify the globals (as the format changed in a breaking way in a minor version of Luacheck). It also updates the generated `stds.garrysmod` globals with `generate-luacheck.sh` (and adds some variables, like `CLIENT` and `SERVER`, that aren't documented on the Garry's Mod wiki), and teaches Luacheck about some global variables we intentionally use (but shouldn't).

Results of `git ls-files | grep '\.lua$' | xargs luacheck --std min+garrysmod+wiremod`:
Before: `Total: 12223 warnings / 189 errors in 403 files`
After: `Total: 2257 warnings / 189 errors in 403 files`

### CODE REVIEW

**Comment by AbigailBuccaneer** [comment]
(FYI @TomyLobo I've set the repository to disallow squashes and rebases from pull requests, and to require an approved review.)

**Comment by Divran** [comment]
@TomyLobo review this k

**Comment by TomyLobo** [comment]
oh didnt see this was a new PR. thought this was still mine :D

which vars came from the tutorials?

**Comment by TomyLobo** [comment]
also, i think garry generates the docs from source, so they're always up-to-date.
I guess the tutorials could be outdated or at some point become outdated?
If we use outdatd gmod vars, we want to know

**Comment by AbigailBuccaneer** [comment]
No vars came from the tutorials; it just gave an 'unrecognized section' warning so now it's ignored.

**Comment by AbigailBuccaneer** [comment]
@TomyLobo LGTY?

**Comment by TomyLobo** [comment]
You're potentially solidifying a state of affairs we should (according to your comments) change at some point, but ultimately it's your call.
other than that, looks good to me

**Comment by AbigailBuccaneer** [comment]
Filed #1387 to address the TODOs.

**Pull request merged**
