### PR TITLE
Update gmod_wire_cd_disk.lua

### PR DESCRIPTION
**Pull request by thegrb93**
@AlexALX @TangentDelta 

Can you try this and see if it works better?

### CODE REVIEW

**Comment by TangentDelta** [comment]
This change causes the layout of the TrackSectors table to change completely, which changes the geometry of the disk and breaks compatibility with any contraptions that rely on the old geometry.

Before this pull request, the table looks like this for the medium CD:
```
2	=	0
3	=	13
4	=	32
5	=	58
6	=	90
7	=	128
```
With this commit, the table ends up looking like this:
```
3	=	0
4	=	7
5	=	20
6	=	39
7	=	65
8	=	97
9	=	135
```

**Comment by TangentDelta** [comment]
stuff

At the moment the CD uses a zone density sector arrangement, as shown on the right of the diagram. This makes it somewhat annoying to work with, and requires us to use look-up tables and geometry calculations to figure out how many sectors there are per track.

If we wanted to make things simpler, we could use standard geometrical sectors as shown on the left. This could be implemented into a new "disk platter" entity, or a check box in the Wire CD to tell it which sector layout to use.

**Comment by thegrb93** [comment]
Feel free to suggest corrections. I'll try to test it too when I get a chance.

**Comment by TangentDelta** [comment]
What does your pull request fix? Did somebody report a problem with my tweak that got merged in?

**Comment by thegrb93** [comment]
They commented on your commit (though they should've opened an issue) https://github.com/wiremod/wire/commit/07fb444ccf889a27109a88314535a8e0d45cbf89

**Comment by TangentDelta** [comment]
I see, so my change makes the outer-most track unusable. I didn't think it would be a problem since going out that far caused the incorrect track to be reported, making it practically unusable.

**Comment by Anticept** [comment]
How about this idea:

You have different CD disks that you can set the parameters on in the wire menu before you spawn them. Legacy disks would have no such parameters set, so they would default to the old disk sector arrangement automatically.

**Comment by TangentDelta** [comment]
> How about this idea:
> 
> You can configure disks with parameters in the wire menu before you spawn them. Legacy disks would have no such parameters set, so they would default to the old disk sector arrangement automatically.

Yes, this is what I was suggesting with my geometric disk sectoring idea. Have a drop-down with like 3 different CD types. "Legacy", "Zone-Bit Sectors", and "Geometrical Sectors". Also, have a way to read the geometry from the disk so that people don't have to calculate it by hand to find out where the sectors are located.

**Comment by thegrb93** [comment]
> Also, have a way to read the geometry from the disk so that people don't have to calculate it by hand to find out where the sectors are located.

Isn't that the point of the 'track' and 'sector' outputs? So that your contraption has to manually seek the sectors using trial and error like a real cd?

**Comment by AlexALX** [comment]
> Isn't that the point of the 'track' and 'sector' outputs, so that your contraption has to manually seek the sectors using trial and error like a real cd?

I think he talked about providing proper disk geometry info instead of incorrect one what we have right now - wrong tracks and sectors number + if you will add new "layout" types then way to detect which layout type it is. 

Anyway as i said - can check commits and give maybe other suggestions on weekend. This cd changes is way critical for me - don't want to waste few months of development my PC/OS if changes will make it useless.

**Comment by TangentDelta** [comment]
> Isn't that the point of the 'track' and 'sector' outputs, so that your contraption has to manually seek the sectors using trial and error like a real cd?

Real-life CD-ROM drives are able to extract some information from the "ATIP" [Wikipedia Page](https://en.wikipedia.org/wiki/Absolute_Time_in_Pregroove)

**Comment by thegrb93** [comment]
Yeah, the 'track' and 'sector' outputs are considered to be the ATIP

**Comment by TangentDelta** [comment]
> Yeah, the 'track' and 'sector' outputs are considered to be info extracted from the ATIP

The ATIP also tells the drive how many sectors there are in the spiral track, which is information that you cannot access right now from the Wiremod CD-ROM entity.

**Comment by thegrb93** [comment]
You can infer that info by rotating the track and finding the largest sector index.

**Comment by TangentDelta** [comment]
> You can infer that info by rotating the track and finding the largest sector index.

Sure, but there's no way to read out how many **total** sectors there are on the disk.

**Comment by AlexALX** [comment]
Guys, you talking in wrong direction. I need to have "API" what will provide track/stack number for given sector. lets say i want get info from sector 125903, i need to know on what track/stack it is. So for this i'm calculating on cd drive init (in e2) key-value table what have "sector number " = [track, stack]. something like this. then i can move head to given track/stack and read needed sector. Just want to avoid this initial calculation and get proper way to get this info besides own key-value table.

**Comment by thegrb93** [comment]
Right.. my idea was just starting at track 0 and scanning the cd to create your map by using track/sector outputs. Typically inserting a new cd into a drive will trigger a scanning routine. I'm not against adding more info but it takes away a bit of the challenge if you have everything.

**Comment by AlexALX** [comment]
And what point of this if real disks have known geometry in reality? Like cd/dvd etc. Its not different on each disk type... Scaning like you saying - is like you have to read all sectors in whole real disk - will be waste on time and no one doing this for speed reasons.

**Comment by thegrb93** [comment]
What's the point in using a wire CD then when you can just rotate a regular prop and know exactly its sector will be based on its rotation angle? The point of the wire CD is to pose the challenge of making a system that can physically read/write memory using controllers and searching algorithms.

**Comment by thegrb93** [comment]
> don't make more incompatible changes

The point of this PR is to fix the latest change's incompatibility issue. Just have to test it and figure it out.

**Comment by TangentDelta** [comment]
Just undo my changes then. If I want to implement a "correct" disk geometry model, I can add it in myself later.

**Comment by thegrb93** [comment]
Ok, turns out I had a fundamental misunderstanding of how the sectors are numbered in this entity. I thought their numbering started at 0 for each track.

**Comment by thegrb93** [comment]
So yeah, I think my comments on your original PR are right then. You're just mistaking that the track numbering starts at 0.

**Comment by thegrb93** [comment]
I've reverted the commit and cleaned up the comments from // to -- so it should be safe to merge.

**Comment by AlexALX** [comment]
Can this be pushed to workshop? since my addon is remain broken until that.

**Comment by Anticept** [comment]
Updated.

**Pull request merged**
