### PR TITLE
E2 Mass Problem?

### PR DESCRIPTION
**Pull request by TheMerkyShadow**
I was brought attention to this problem which is described on the r/wiremod subreddit located [here](https://www.reddit.com/r/wiremod/comments/na2067/new_update_causing_problems_with_e2entites/)

I tried a few solutions myself to this problem and this seems to work.

### CODE REVIEW

**Comment by Divran** [comment]
massCenter and massCenterL needs to output a vector (or in E2's case, optionally a table with 3 numbers, as can be seen just below the lines you modified)

**Comment by TheMerkyShadow** [comment]
> massCenter and massCenterL needs to output a vector (or in E2's case, optionally a table with 3 numbers, as can be seen just below the lines you modified)

I totatlly missed that. Alright that should be fine now.

**Comment by thegrb93** [comment]
validPhysics was replaced so that non VPHYSICS movetype things like players/npcs can have their mass measured. Just add a check for nil.

**Review by thegrb93 — APPROVED** [review]

**Comment by thegrb93** [comment]
Looks good. Thanks

**Pull request merged**
