### PR TITLE
added simple anti spam check to setname

### PR DESCRIPTION
**Pull request by Divran**

### CODE REVIEW

**Comment by thegrb93** [comment]
This doesn't call SetOverlayText anymore, does it still work?

**Comment by Divran** [comment]
Yes it does. <https://github.com/wiremod/wire/blob/6d6bb3e6a069de8f1871ca784c7993d1c8c55a42/lua/entities/gmod_wire_expression2/core/selfaware.lua#L113>

**Comment by thegrb93** [comment]
Ah, ok. Still I'm curious how many e2 it takes with this to bring a server down. May test that in a bit.

**Review by thegrb93 — APPROVED** [review]
The code looks fine though.

**Pull request merged**
