### PR TITLE
Refactor clutch. Fixes: #2286

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by thegrb93** [comment]
Replaced the ballsockets with PhysicsSimulate

**Comment by TheLight91** [comment]
Just tested the latest fix on this and it didn't work. Still feels like the clutch doesn't release and still throws the whole vehicle around while not locking the wheels.

At this point I think it's better if Clutch is left alone, at least now it works properly in mp where it matters.

**Comment by thegrb93** [comment]
@TheLight91 once I get the behavior matching the original, I'm still merging because the original's performance was terrible

**Comment by TheLight91** [comment]
Well yes, if the fix is at least on par with how it works now. In Multiplayer is perfect as is now, if the fix destroys that, it's a downgrade though. Or you can have normal behavior for multiplayer and the new one for single player.

**Pull request closed without merging**
