### PR TITLE
Added hydraulic functions

### PR DESCRIPTION
**Pull request by Scottyprogrammer**

### CODE REVIEW

**Comment by Scottyprogrammer** [comment]
All of these function were tested and are functional.

**Comment by its-suun** [comment]
https://github.com/wiremod/wire/wiki/Coding-style

**Comment by Divran** [comment]
Only problem with the coding style I can see in this is the garry-added or
"||" which should be using normal lua's "or"

**Comment by Scottyprogrammer** [comment]
I followed the same syntax as all the other functions in there. What's the particular issue?

**Comment by bigdogmat** [comment]
Take a look at the coding style

**Comment by Scottyprogrammer** [comment]
I did indeed, but other than the or with bars that Div pointed out I don't see an issue. That's why I asked what it was specifically. I also noted that the way I wrote is the same as how the file was previously written.

**Comment by bigdogmat** [comment]
When you add code you write it in the new style. As for the current issues, you're using ! instead of not

**Comment by Scottyprogrammer** [comment]
Ok, do you want me to clean up the file of all ! or just the portions I've written?

**Comment by Divran** [comment]
Just the parts you added is fine

**Comment by Scottyprogrammer** [comment]
Alright, updated all my requested.

**Comment by TomyLobo** [comment]
Guys, don't be like "Take a look at the coding style"!
You already figured out what was wrong, so just tell them!

**Comment by Scottyprogrammer** [comment]
Thanks Tomy, that's what I was after.

**Comment by Scottyprogrammer** [comment]
If this looks good can we merge it? It has been tested

**Comment by Divran** [comment]
@Scottyprogrammer this PR now has conflicts, probably due to me merging your other PR. Pls fix

**Comment by TomyLobo** [comment]
![fix it!] (https://media.giphy.com/media/l41lPzvoHCKXBpK2A/giphy.gif)

**Comment by Scottyprogrammer** [comment]
Ok... I'm having issues syncing my fork/branch with the Wire master. I might fix it and open a clean pull request. Is that ok?

**Pull request closed without merging**
