### PR TITLE
Prompt user when saving a new file in the E2 editor would overwrite an existing one

### PR DESCRIPTION
**Pull request by marchcain**
Redone since the last pull request contained an unrelated commit

fileprompt

### CODE REVIEW

**Comment by Aws0mee** [comment]
I feel like this could get annoying since you’d have to click yes every time you update your E2. Maybe make it a convar or something?

**Comment by Divran** [comment]
that seems like an *extremely* hacky way to remove blur. It'd be less hacky to create your own popup from scratch. Are you sure there's no official gmod way to do this?

**Comment by Divran** [comment]
there is. if you look at the source code here: <https://github.com/Facepunch/garrysmod/blob/be251723824643351cb88a969818425d1ddf42b3/garrysmod/lua/derma/derma_utils.lua#L177> you can see that the Derma_Query function returns the window. And here <https://github.com/Facepunch/garrysmod/blob/be251723824643351cb88a969818425d1ddf42b3/garrysmod/lua/derma/derma_utils.lua#L110> you can see this is how it's enabling the blur. This means to disable it all you need to do is this:
```lua
local pnl = Derma_Query(stuff)
pnl:SetBackgroundBlur(false)
```

**Review by Divran — CHANGES_REQUESTED** [review]
see latest comment for required changes

**Review by Divran — APPROVED** [review]

**Pull request merged**
