### PR TITLE
Remove legacy wire tool

### PR DESCRIPTION
**Pull request by immibis**
It has to go eventually, right?

Wire Advanced is the new wire tool, so it's relabelled as simply "Wire". The ID is not changed - it's still wire_adv.

### CODE REVIEW

**Comment by Nebual** [comment]
I approve, but I'll leave merging to someone else since this is inevitably controversial for some reason.

**Comment by Divran** [comment]
The only argument there is against this is the fact that the wire legacy tool is simpler. It doesn't have nearly as many features, and therefore is less likely to break. In the past, before my adv wire rewrite, the adv wire tool was riddled with bugs, and having the legacy wire tool was a life saver when the adv wire tool decided to not work. But my version of the adv wire tool hasn't broken down a single time since it was made, so it's probably pretty stable.

**Comment by AbigailBuccaneer** [comment]
We've been saying "let's keep the legacy wire tool around in case the advanced wire tool breaks" for years now. It's time to chuck it in my opinion :+1:

**Comment by brandonsturgeon** [comment]
`It has to go eventually, right?`
Well, it doesn't _have_ to..

I wonder how many people rely on the tool name for wire advanced for stuff. I currently have a keybind that switches to wire advanced, so I'll have to change that. But if I have that, other people certainly have stuff too.

**Comment by bigdogmat** [comment]
> I wonder how many people rely on the tool name for wire advanced for stuff. I currently have a keybind that switches to wire advanced, so I'll have to change that. But if I have that, other people certainly have stuff too.

The tool id wasn't changed, just the name was.

**Comment by arduinium** [comment]
I agree for deletion, I rarely use any wiring tool anyway...

**Comment by immibis** [comment]
@brandonsturgeon Your keybind will still work. The tool is still called wire_adv - just the displayed label is changed.

**Comment by brandonsturgeon** [comment]
Ah good to know, sorry I didn't check the changes first.

**Comment by oldmud0** [comment]
Delete.

**Comment by suunrider** [comment]
> Delete.

**Comment by AbigailBuccaneer** [comment]
Unless anybody has any objections I'd like to get this in the next Workshop release. We gotta have one thing that'll confuse our users each release :wink:

**Comment by AbigailBuccaneer** [comment]
Let's do this!

**Comment by TomyLobo** [comment]
![But why?] (http://www.reactiongifs.com/r/but-why.gif)

**Comment by TomyLobo** [comment]
Can't you just remove it from the tool list but keep it in for "gmod_tool wire"?

**Comment by thegrb93** [comment]
I haven't used old wire tool for years. Why keep it?

**Comment by oldmud0** [comment]
Maybe alias the old wire tool to advanced wire?

**Comment by TomyLobo** [comment]
That's not what I meant.
The reason tools like wire_adv, my wire_improved and divran's wire tool could be written and improved is that there was always a fallback, allowing you to go ahead and potentially break stuff in the process.
If I counted correctly, the removal of that fallback means we only have one wire tool and if we break that, there's none left, meaning we'll have to tread on eggshells while making changes to it.

**Comment by Divran** [comment]
it will always be in the github repo, though, so I suppose that if we break
the wire tool we can make a commit that brings it back or something. but
yeah that is the same reason I haven't deleted it

**Comment by TomyLobo** [comment]
we can - users can't

**Comment by immibis** [comment]
We should bring back the pod controller so people can use it in case the advanced pod controller stops using.

**Comment by TomyLobo** [comment]
it's more likely that the pod controller stops working :)

**Comment by AbigailBuccaneer** [comment]
> The old wire tool also mirrors the respective wirelib api pretty closely.
It's probably the other way round and that might actually be a reason to get rid of it.
But in that case, I'd expect the person who removes the tool to refactor the API to be more in line with what it represents, as opposed to how the legacy wire tool is phased.

I had a branch around in which I was looking at rewriting the WireLib API to be less awful. There's so much cruft!

**Comment by immibis** [comment]
We need to be able to select between the current WireLib and Abigail's WireLib at runtime, just in case the new one has any bugs. /s

**Comment by TomyLobo** [comment]
yeah and we need to be able to switch between the winapi for winxp and the winapi for win7 at runtime, just like we can switch between notepad and notepad++ at any time.

**Comment by TomyLobo** [comment]
I have since learned that switching winapi versions is actually possible. It's exactly what Windows XP and above do in compatibility mode.
Nevertheless it was a shitty comparison :)

**Pull request merged**
