### PR TITLE
Fixed a couple of issues with the wire tool

### PR DESCRIPTION
**Pull request by MulleDK19**
Fixed wires continuing to blink if the tool gun was holstered while aiming at a wire entity.
Moved Wire_GrayOutWires to the WireLib "namespace".
Replaced instances of ent:IsValid() checks with IsValid(ent) in the wire tool.

### CODE REVIEW

**Comment by thegrb93** [comment]
A couple unneeded files got added to your commit. Remove those first.

**Comment by MulleDK19** [comment]
Ugh, yea, they got added by accident. Hang on.

**Comment by MulleDK19** [comment]
Fixed.

**Comment by thegrb93** [comment]
Looks fine to me. I'll give it a little time to see if others have any input.

**Pull request merged**
