### PR TITLE
Get/Set Friction functions for custom friction props

### PR DESCRIPTION
**Pull request by dvdvideo1234**
http://wiki.garrysmod.com/page/Entity/GetFriction
http://wiki.garrysmod.com/page/Entity/SetFriction

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Had those laying around and decide to share them :)

**Comment by arduinium** [comment]
Suggested changes:
```
e2function void entity:propSetBuoyancy( number buoyancy )
	if not PropCore.ValidAction( self, this, "buoyancy" ) then return end
	if E2Lib.isnan( buoyancy ) then buoyancy = 0 end
	local phys = this:GetPhysicsObject()
	if IsValid( phys ) then
		phys:SetBuoyancyRatio( math.Clamp( buoyancy, 0, 1 ) )
	end
end

e2function void propSetFriction( number friction )
	if not PropCore.ValidAction( self, this, "friction" ) then return end
	if E2Lib.isnan( friction ) then friction = 1 end
	this:SetFriction( math.Clamp(friction, -100, 100) )
end

e2function void propGetFriction()
	if not PropCore.ValidAction( self, this, "friction" ) then return end
	return this:GetFriction()
end
```
Try to make your functions as clean and fast as possible ;)

**Comment by Divran** [comment]
It's only necessary when the function the number is given to can't handle nan. For example, I believe setpos and applyforce crashes the game if you give it nan or math.huge, so they have checks for that. So all you have to do is test it without isnan and give it fucked up numbers and if nothing weird happens then it's k

**Comment by dvdvideo1234** [comment]
I cannot test those now. But when I get home soon enough ;)

**Comment by Nebual** [comment]
I think the math.Clamp is probably all SetFriction needs, but it doesn't hurt. Looks fine to commit.

**Comment by arduinium** [comment]
Here is a function I made few days ago, I was about to make another pull request but if you could include it in yours.. ;)

```
__e2setcost(10)

local staticProps = {}
hook.Add( "CanDrive", "wire_expression2_propcore_CanDrive", function( ply, ent ) return staticProps[ent] == nil end )
hook.Add( "EntityRemoved", "wire_expression2_propcore_EntityRemoved", function( ent ) staticProps[ent] = nil end )

e2function void entity:propStatic( number static, number restoreVelocity )
	if not PropCore.ValidAction( self, this, "static" ) then return end
	if static ~= 0 and staticProps[ this ] == nil then
		local phys = this:GetPhysicsObject()
		staticProps[ this ] = {
			wasMotionEnabled = phys:IsMotionEnabled()
			velocity = phys:GetVelocity()
			angVelocity = phys:GetAngleVelocity()
		}
		this.PhysgunDisabled = true
		this:SetUnFreezable( true )
		phys:EnableMotion( false )
		phys:Sleep()
		
	elseif staticProps[ this ] ~= nil then
		this.PhysgunDisabled = false
		this:SetUnFreezable( false )
		if staticProps[ this ].wasMotionEnabled == true then
			local phys = this:GetPhysicsObject()
			phys:EnableMotion( true )
			phys:Wake()
			if restoreVelocity ~= 0 then
				phys:AddAngleVelocity( staticProps[ this ].angVelocity )
				phys:SetVelocity( staticProps[ this ].velocity )
			end
		end
		staticProps[ this ] = nil
	end
end
```

It makes the prop truely static.. It cannot be moved by any mean (that I know of..). The second parameter when set to 1 will allow to restore the velocity at the time it was made static. Personally I use it to make buildings, but I thought it would be nice to add this second parameter, can be useful some other day ;)

**Comment by dvdvideo1234** [comment]
Here is the myghty E2 code xD

@name Test
@inputs 
@outputs 
@persist Ent:entity
@trigger 
@model models/props_c17/FurnitureWashingmachine001a.mdl

runOnTick(1)

File = "Prop_functions_Test.txt"

if(first() || dupefinished())
{
    Ent = entity()
    Str = "Starting \n"
    
    Ent:propTest1(5/0)
    
    Str = Str + "Buoyancy Success \n"
    
    Ent:propTest2(5/0)
    
    Str = Str + "Friction Success \n"
    
    fileAppend(File,Str)
    

}

 Ent:propTest1(1)
 Ent:propTest2(200000)

If My Gmod crashes I will know exactly where it happened ...
So far as it runs this code without crashing I can assume that those functions have internal protection against nasty arguments.

God speed !

**Comment by dvdvideo1234** [comment]
Sure Dude I can add your function it the wire team says its OK ;).

**Comment by Nebual** [comment]
Separate pull requests for separate functionality!

Also that looks interesting, but I think it'd be better to make the
constituent parts all accessible via e2, rather than make a single black
box function. Just one opinion.

**Comment by shadowscion** [comment]
Have you tried these to make sure they actually work (the lua functions themselves, not your e2 functions). The last time I tried them they didn't actually do or affect anything.

**Comment by dvdvideo1234** [comment]
Yep
I floated a washing machine :)

**Comment by dvdvideo1234** [comment]
For

**Comment by arduinium** [comment]
Just noticed that ```e2function void propGetFriction()``` . This is wrong because the function return something, it can't be void. Please test your functions before!

**Comment by dvdvideo1234** [comment]
Good thinking 10x

**Comment by dvdvideo1234** [comment]
What Should I put then ??

**Comment by AbigailBuccaneer** [comment]
Either it should've been squashed into a previous commit, or it should be something like "Removed unnecessary NaN check from propcore functions".

**Comment by dvdvideo1234** [comment]
How should I change it then.. committing again maybe ...

**Comment by AbigailBuccaneer** [comment]
See [here](https://help.github.com/articles/changing-a-commit-message/). Essentially, `git rebase -i HEAD~4`, change `pick` to `reword` for any commits that need rewording, and then `git push -f` your changes.

**Comment by AbigailBuccaneer** [comment]
In fact, you could probably do with `squash`ing some commits too.

**Comment by dvdvideo1234** [comment]
Yeah, second option is more useable for me, because Git for windows does not work for me.

**Comment by dvdvideo1234** [comment]
Will it be OK if I make a new pull request .... All the functions work and it will be 1 commit instead of 5

**Comment by AbigailBuccaneer** [comment]
@dvdvideo1234 there's no need to do a new one, as you should be able to force-push a different history to the `dvdvideo1234:master` branch. But I won't complain if it's easier for you to do that.

**Comment by dvdvideo1234** [comment]
I thing we are done :)

**Comment by dvdvideo1234** [comment]
Kk, making a new PR

**Pull request closed without merging**
