### PR TITLE
Refactor entity indexing. Fixes: #1152

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by Divran** [comment]
This would change the behavior of storing values entities. Previously if you deleted the e2 the values would still be there

**Comment by thegrb93** [comment]
They have always been indexed by the uid of the e2 though so, yeah, they would still be there, but inaccessible.

**Comment by thegrb93** [comment]
Assuming self.uid is unique for each e2?

**Comment by Divran** [comment]
IIRC uid is the player's. On phone atm can't check

**Comment by Divran** [comment]
https://github.com/wiremod/wire/blob/67310ee2c17e1e4722ed8ddb12b13861f832034c/lua/entities/gmod_wire_expression2/init.lua#L458
and
https://github.com/wiremod/wire/blob/67310ee2c17e1e4722ed8ddb12b13861f832034c/lua/entities/gmod_wire_expression2/init.lua#L354

**Comment by thegrb93** [comment]
Thoughts on imposing this restriction? The current method bypasses the 'emergency ram' cleanup.

**Comment by Divran** [comment]
Instead of placing it on the e2, why not a table local to the file, indexed by player uid and the target entity. That way we retain old behavior and cleaning it in the emergency RAM hook becomes easy.

**Comment by thegrb93** [comment]
Haven't tested but I think something like this should work

**Comment by Divran** [comment]
Now you're indexing it by player instead of player uid which means it'll no longer persist through disconnects

**Comment by thegrb93** [comment]
When does it get cleaned then?

**Comment by Divran** [comment]
Saw your deleted post about when it gets deleted, it was still emailed to me and I just want to respond to that by saying that I'm just playing devil's advocate here. For me personally it wouldn't really matter much if the behavior changed slightly, but I imagine it would matter for others. And since keeping the old behavior is so easy, why not keep it? As to when it gets cleaned, the answer is never. Unless emergency ram clear is enabled. But the same is also true for global vars already as well as several other things in E2.

**Comment by thegrb93** [comment]
Ok, this should work then. Will test later

**Comment by thegrb93** [comment]
It's working now

**Pull request merged**
