### PR TITLE
Don't let wire use missing materials

### PR DESCRIPTION
**Pull request by thegrb93**
Otherwise extreme lag happens to clients.

Copied with permission from https://github.com/wiremod/wire/pull/1966

### CODE REVIEW

**Comment by shadowscion** [comment]
Does this mean we can only use materials that are in the override list, or does it literally check for missing files?

**Comment by thegrb93** [comment]
It checks for missing files. @brandonsturgeon was supposed to open a new pr

**Comment by brandonsturgeon** [comment]
Got caught up with IRL stuff - putting this back on my prio list

**Comment by brandonsturgeon** [comment]
Just got back from vacation, let me gather context on this again and I'll update this thread no later than Wednesday, 5pm PST.

**Comment by brandonsturgeon** [comment]
Alright, so it seems like it doesn't matter if it's a PNG or not. This PR works as-is for _most_ materials, but there are a certain set of built-in materials (for gmod and other mountable games) that exist clientside but not serverside. These include things like button images for GUI stuff. The client will have those, but the server will not.

I have a list of material directories that exist serverside but not clientside, I'll run them by you over Discord before opening a new PR including those exceptions, and a way for server owners to manually whitelist certain paths.

**Comment by brandonsturgeon** [comment]
Working on this again.. I'm going to work on whitelisting the valid gmod materials, but that still won't be perfect due to addons and such. We'll figure something out.

**Comment by thegrb93** [comment]
Remove this since no longer needed. https://github.com/Facepunch/garrysmod-issues/issues/511

**Pull request closed without merging**
