### PR TITLE
Made wire latch's weld save with duplicator

### LINKED ISSUE #1830: Make wire latch's weld dupable
Will fix constraint system issues if it is saved with the dupe.

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes #1830

### CODE REVIEW

**Comment by thegrb93** [comment]
@TheLightBringer1991 would you mind testing this? I don't want to merge it without knowing if it breaks your tanks.

**Comment by TheLightBringer1991** [comment]
sure, I'll test as soon as I can.

**Comment by TheLightBringer1991** [comment]
Just tested, breaks stuff in a very similar way (if not the same) as when you made the latches wait to add their weld.

**Comment by thegrb93** [comment]
With or without constraint sorting?

**Comment by thegrb93** [comment]
Works fine for me without constraint sorting.

**Comment by TheLightBringer1991** [comment]
Breaks with both options.

**Comment by thegrb93** [comment]
Well before, the latch welded first, but now it welds in the order it was made like all the other constraints. The only reason it worked before was a fluke. I'm not really sure I want to sacrifice new consistent behavior over preserving old stuff that only worked by fluke.

Can you try with a new setup and see if it works well?

**Comment by thegrb93** [comment]
If it still fails, I'll investigate. Otherwise I may merge it if no one else has input.

**Comment by thegrb93** [comment]
Also, old dupes will have the latch weld last since the dupe never saved a weld. So that's why you're seeing the same behavior as the previous merge.

**Comment by thegrb93** [comment]
Because the latch's weld is being applied last in your old dupes.

If we keep the old behavior, then anything new that's made will suffer from the latch's weird (always go first) behavior and break new stuff that's made.

**Comment by thegrb93** [comment]
I guess I can add a backwards compatibility variable but that's all I'm gonna do for it.

**Comment by thegrb93** [comment]
Try that

**Comment by TheLightBringer1991** [comment]
Well, now old stuff works fine if you just spawn it and use it. So the backwards compatibility works.

As soon as you dupe and spawn a creation, the new latch behaviour is applied, right? And that's when stuff goes weird. Yes, it is more constistent, but still constintently weird.

Isn't it better to wait for the other stuff to be fixed before pushing it though? So everything works and it is done? I mean, if you push the update before https://github.com/Facepunch/garrysmod/pull/1556 is applied, we will have weird working stuff for a while.

Right now I am the only one with weird problems, but it is also because I'm the only one testing the new stuff. Many people just use the workshop version or just svn update the folder without looking into it. I see many people that come up with weird "rituals" to build stuff to get around bugs and they don't report them as issues here, they just say "That's how it is". We need more people to test stuff, that report problems or help with coding if they can, so we can iron out bugs faster, and by having a bigger pool of testers it's easier to see if it's an actual bug or just something weird happening with a particular build. I test the stuff with all my acf stuff to be sure it's not a problem with that one thing in particular, but still it is not a huge amount of stuff, it's around 10 creations.

**Comment by thegrb93** [comment]
If you can help me investigate what is consistently weird, I can fix it. The Facepunch/garrysmod#1556 issue affects latch regardless of the old or new version. Basically if you have 60 constraints including a latch, you can only flip the latch 40 times before it hits the 100 limit and spawns a new constraint system.

What's worse is these 'rituals' lead to incorrect stuff getting baked into their saves so we have to make backwards compatibility like in this case.

**Comment by TheLightBringer1991** [comment]
I am not a coder, so I can't help with that. All I can do is actually build and see what happens. So I can't go in detail on how it is breaking and why. Do you have a server where we can test stuff directly? So maybe you can see if I am the one somehow doing something wrong or it's an actual bug.

**Comment by thegrb93** [comment]
I mean just describe what weirdness is happening or provide a dupe. I do have a server, but have to go to bed now. You can find me on 66.150.214.126:27015

**Comment by thegrb93** [comment]
And https://steamcommunity.com/id/sparkybird/

**Comment by TheLightBringer1991** [comment]
Going to bed soon too. I will add you we can see togheter how and why shit fucks up, when we both have time.

**Comment by thegrb93** [comment]
K

**Comment by thegrb93** [comment]
Ok I know what's wrong. I need to make the weld's creationid match the latch controller's creationid.

**Comment by thegrb93** [comment]
The new changes pass all my tests. Just have to do a over 100 constraint test

**Comment by thegrb93** [comment]
Note to self: forgot to push new changes.

**Comment by thegrb93** [comment]
Just going to leave it to its old stupid behavior. Backwards compatibility is too big of an issue.

**Pull request closed without merging**
