### PR TITLE
Made wire latch wait until finished duping before applying constraint

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #1825

### CODE REVIEW

**Comment by TheLightBringer1991** [comment]
With it the latches spawn all welded, should spawn unwelded.

**Comment by thegrb93** [comment]
Yeah I think I just thought of a better way this could be implemented.

**Comment by thegrb93** [comment]
Instead of blocking TriggerInput, block the weld function instead, then apply the weld with the entity's settings after dupe is finished.

**Comment by thegrb93** [comment]
@TheLightBringer1991 try that

**Comment by TheLightBringer1991** [comment]
Going to bed now, will try first when I wake up.

**Comment by TheLightBringer1991** [comment]
Well, the latches instantly break with the latest dupe2 update after I spawn a tank, don't even change anything, dupe it and respawn it. So I can't really tell you if this is any better. Got to try and redo constraints and a tank and see what happens.

**Comment by thegrb93** [comment]
They don't break when I pasted them ovO

**Comment by TheLightBringer1991** [comment]
I mean when I paste a tank from my dupe folder, dupe it and paste it again. The new duped one's weld latches go bad.

**Comment by thegrb93** [comment]
I'm thinking maybe its getting a new constraintsystem due to hitting the constraint limit.

**Comment by thegrb93** [comment]
Toggling the weld latch on and off too many times will have the same effect until this is applied. https://github.com/Facepunch/garrysmod/pull/1556

**Comment by thegrb93** [comment]
@TheLightBringer1991 is it still not working or can I merge it?

**Comment by TheLightBringer1991** [comment]
Still does the same, but the problem comes from the dupe2 update, not from this. Can't really tell if it's better.

**Comment by TheLightBringer1991** [comment]
Right now I am reapplying constraints to a tank and see if it works

**Comment by TheLightBringer1991** [comment]
[Test.txt](https://github.com/wiremod/wire/files/2776184/Test.txt)

Here try this and see. Latches instantly shit themselves right at spawning. In this tank I redid every constraint, twice. Same result. I don't know wtf is going on, but it's even worse than before.

**Pull request merged**
