### PR TITLE
fix data store after 11 years

### PR DESCRIPTION
**Pull request by sekta2**

### CODE REVIEW

**Comment by sekta2** [comment]
Looks like I did something wrong, well the Data Store seemed to work correctly but it had no output data.

**Comment by Denneisk** [comment]
I don't understand what you're trying to do here. What you posted is functionally equivalent (although less likely to be optimized properly by the JIT).

**Comment by thegrb93** [comment]
Does anyone know what this entity is supposed to do? Does it just store inputs and output them?

**Comment by Vurv78** [comment]
> Does anyone know what this entity is supposed to do? Does it just store inputs and output them?

https://web.archive.org/web/20160801175345/http://wiki.wiremod.com/wiki/Store

https://web.archive.org/web/20160801204010/http://wiki.wiremod.com/wiki/Transferer

Wiki pages were luckily archived

**Comment by thegrb93** [comment]
Either that or in the memory gates.

**Comment by thegrb93** [comment]
If they aren't working as well, then I vote we delete them.

**Pull request closed without merging**
