### PR TITLE
Added hydraulic functions

### PR DESCRIPTION
**Pull request by Scottyprogrammer**

### CODE REVIEW

**Comment by Scottyprogrammer** [comment]
This reflects all changes in Pull Request #1203, but it was messy, so I had to redo my branch.

**Comment by Scottyprogrammer** [comment]
Thanks so much @Divran and @TomyLobo. Can't wait to use these functions.

**Comment by Scottyprogrammer** [comment]
Now if server would update wiremod that would be nice.

**Comment by TomyLobo** [comment]
This would have to hit the workshop first

**Comment by Scottyprogrammer** [comment]
Yeah I noticed it wasn't updated in a while, how do I get it on there? How often does this Git get put on the workshop?

**Comment by bigdogmat** [comment]
Whenever this branch gets merged with the workshop one

**Comment by oldmud0** [comment]
And somebody generates a zipball and uploads it

**Comment by TomyLobo** [comment]
@oldmud0 actually that part is automated

**Comment by oldmud0** [comment]
"automated"

**Pull request merged**
