### PR TITLE
Trim all trailing whitespace

### PR DESCRIPTION
**Pull request by wrefgtzweve**
Trims all trailing whitespaces from lua files. Mainly improves style but it will also slightly increase joining speeds on servers i think, which is always welcome.

The linter will likely try to kill me because i only changed whitespaces so any files that haven't been properly styled yet will be flagged as bad.

### CODE REVIEW

**Comment by Denneisk** [comment]
Lightning fast server startups here we come

**Comment by wrefgtzweve** [comment]
> Lightning fast server startups here we come

A whopping ~0.03s faster 💪

**Comment by thegrb93** [comment]
It this was the 70s, maybe lol

**Comment by wrefgtzweve** [comment]
> If this was the 70s, maybe lol

lua is sent over a 64kb/s max channel sadly as far as i know

**Pull request merged**
