### PR TITLE
Add getCollisionGroup and setCollisionGroup

### PR DESCRIPTION
**Pull request by Vurv78**
Resolves https://github.com/wiremod/wire/discussions/2749

## RFC

Should this deprecate `noCollideAll` ?

### CODE REVIEW

**Comment by Vurv78** [comment]
Both lints are caused by the ExtPP, funny..

really need https://github.com/wiremod/wire/pull/2555 merged

**Review by thegrb93 — APPROVED** [review]

**Comment by Denneisk** [comment]
`noCollideAll` is a bit more intuitive but my concern is people demanding for constraintcore to be enabled just for that function, so it probably should be just for that (or move `noCollideAll` out of constraintcore and keep it since it's not really that bad of an alternative).

**Comment by Vurv78** [comment]
That seems fair

**Comment by Denneisk** [comment]
The way I see it, creating `setCollisionGroup` and moving `noCollideAll` are basically the same thing.

**Pull request merged**
