### PR TITLE
Remove E2

### PR DESCRIPTION
**Pull request by yogwoggf**
Hardly used chip. Working on making a new one. E2 has countless vulnerabilities that make it easy to crash servers. E2 also annoys most players. Most servers have E2 completely disabled anyways.

### CODE REVIEW

**Comment by Vurv78** [comment]
Funny.

**Comment by yogwoggf** [comment]
Why was this closed? You removed three chips without asking the community, or getting more PR reviews, or even just letting it simmer for a while. Surely I can do the same?

**Comment by thegrb93** [comment]
zcpu was being abused on servers because of holes in its security. Nobody was willing to fix it.

**Comment by thegrb93** [comment]
Quit being an ass

**Comment by yogwoggf** [comment]
> zcpu was being abused on servers because of holes in its security. Nobody was willing to fix it.

E2 has also been abused on many servers because of major holes in its security (and design). No one is *also* willing to fix it despite these issues being prominent in the wiremod community.

Almost every major server has disabled E2 in some form or another.

**Comment by yogwoggf** [comment]
> Quit being an ass

???

That was not professional, and you just attacked me for no reason?

**Comment by Hazeofdream** [comment]
major servers disable e2 because they paywall it or don't want to moderate it, not being it's abusive lol

**Comment by PPGamingDK** [comment]
You are stupid.

**Comment by yogwoggf** [comment]
> major servers disable e2 because they paywall it or don't want to moderate it, not being it's abusive lol

"don't want to moderate it"
I dont know how you just invalidated your own point

**Pull request closed without merging**
