### PR TITLE
Update Wire clutch. Fixes: #2123

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Review by thegrb93 — APPROVED** [review]

**Comment by bigdogmat** [comment]
This shouldn't be necessary, that table should always exist as it's created in Init and never remove.

**Comment by dvdvideo1234** [comment]
@bigdogmat 

Sure. [If you say so](https://github.com/wiremod/wire/issues/2123) ;)

**Comment by thegrb93** [comment]
Will try to reproduce with https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/gamemode/persistence.lua#L57

before merging

**Comment by thegrb93** [comment]
Couldn't reproduce

**Pull request closed without merging**
