### PR TITLE
Add E2 intersection()

### PR DESCRIPTION
**Pull request by CornerPin**
With this funcion you can find intersection point of two lines. I think it may be useful.
image

### CODE REVIEW

**Comment by Divran** [comment]
If you're going to add this, you should add a whole library for it to do intersections between many different surfaces/shapes. And such a library already exists: https://github.com/wiremod/wire-extras/blob/master/lua/entities/gmod_wire_expression2/core/custom/tracesystem.lua

**Comment by oldmud0** [comment]
Isn't like half the stuff in wire-extras broken anyway?

**Comment by bigdogmat** [comment]
@oldmud0 I don't think I've had issues with anything in wire-extras

**Comment by thegrb93** [comment]
Linear least squares library might be useful

**Pull request closed without merging**
