### PR TITLE
Added e:getPlayerColor() and e:getWeaponColor()

### PR DESCRIPTION
**Pull request by TwistedTail**

### CODE REVIEW

**Comment by CornerPin** [comment]
`getWeaponColor` was rejected in #1340.

**Comment by TwistedTail** [comment]
In that case, I hope it gets added this time.

**Comment by thegrb93** [comment]
Could probably be added because who cares what gets added to it at this point.

**Comment by shadow7483147** [comment]
just went ahead and looked this up in case there was a doubt that this wasn't just something you could just do with e:color()

these functions are meant to return the colors players set as their playermodels/physgun color, which normally can't be returned from an entity.

only question is, why tho?

**Pull request merged**
