### PR TITLE
Add non-ASCII character support to Expression 2 Editor

### LINKED ISSUE #824: Non-ASCII characters aren't allowed in the E2 editor
Hello!
Can you add in E2 editor support of Unicode characters(like as cyrillic)?
I can add them in external editor(like as Notepad++), but why additional problems?
Regards and sorry for my bad English.

### PR DESCRIPTION
**Pull request by stepa2**
изображение

Fixes #824 

Note: Multiple-codepoint symbols are (will be, not tested) treated as separate symbols.
This is hard-to-fix (garpheme cluster handling required AFAIK) and will not be fixed in this PR.

- [x] Fix bug: Text search works incorrectly
- [x] Fix bug: Non-monospaced font for non-ASCII characters casuse caret to "drift away"
- [x] Fix bug: when console is opened with active editor, and keyboard layout is not english, character is written to the editor
- [x] Fix bug: caret can not be moved after character before last character in line
- [x] Fix bug: game freezes (infinitive loop?), related to matching brackets highlighting
- [x] Improve peformance: small freezes when scrolling with arrows (on some lines)
(related to autocompletion, also occurs when scrolling over keywords)
- [x] Fix bug: scrolling is broken
- [x] Fix bug: invalid UTF-8 code in getMatchingCharacter
- [x] Fix bug in matching brackets highlighting
- [x] Fix bug: selecting with double click not selects last character
- [x] Fix bug: text in last 3 lines is not highlighted
- [x] Fix bug: syntax highlighting of new text breaks 
- [x] Fix bug: double-click selection breaks when trying to select 'Тест' in
    ```
    local Тест = 1
    print(Тест)
    ```
- [x] Fix bug: double click selection includes space before newline but should not
  - Can not reproduce
- [x] Fix bug: non-ASCII characters sometimes not rendered, related to syntax highlighting 
- [x] Improve FPS: The longer text in total, lower FPS is
- [ ] Improve FPS: when selecting text at the end of long line
- [ ] TODO: Cache all lines of the file on opening (to fix `Line XX not exists or not cached` error)

### CODE REVIEW

**Comment by stepa2** [comment]
Also can someone help me to make commit list clean?
How to remove all that commits expect f360cf0?

**Comment by thegrb93** [comment]
`git rebase -i master` then change all commits except for the one you want to 's' which will squash them.

**Comment by stepa2** [comment]
What do 's' means here?

**Comment by thegrb93** [comment]
s is short for squash

**Comment by stepa2** [comment]
Code is ready-to-merge

**Comment by thegrb93** [comment]
Ok, will test soon.

**Review by thegrb93 — CHANGES_REQUESTED** [review]
I tried this code, but it seems to break rendering and give an error 'Unknown character'

```
🦜 = 123
print(🦜)
```

**Comment by stepa2** [comment]
It seems that this can not be fixed (on Windows, at least), because VGUI not renders UTF-16 surrogate pairs correctly.
U+10000 is 𐀀 (if not rendered correctly with default font, see [here](https://unicode-table.com/en/10000/)).
`lua_run print(utf8.char(0x10000))` prints two hollow squares.
изображение
On the contrary, U+FFFD (�) is rendered correctly.
изображение

**Comment by thegrb93** [comment]
The two squares are okay, but the rendering around them is also messing up. Also why's the invalid character error happening?

**Comment by thegrb93** [comment]
@stepa2

**Review by stepa2 — COMMENTED** [review]
Fixed

**Comment by stepa2** [comment]
I think it is ready to be merged now

**Comment by thegrb93** [comment]
Will look again maybe tonight

**Comment by Vurv78** [comment]
Rendering works perfectly for me (besides not seeing the emojis being a windows issue)

Small issues:
* You can't double click on blocks of unicode to select that chunk, dunno if that's possible for you or if you intend to support that (you can just select it manually anyway, just a little inconvenience)

* And the highlighting/tokenizer doesn't support unicode in identifiers (not really important for me once again just saying)

All I really care about now is just reverting the auto-indent switch from tabs to spaces (hard to tell what changed since the entire text editor file's indentation is now part of the diff), great work tho

**Comment by stepa2** [comment]
- I know about double-click selection bug, fixing it will require some Unicode character database
- Not only tokenizer not supports Unicode identifiers, E2 also not supports it

**Comment by stepa2** [comment]
Most diff viewers (even GitHub integrated one) can ignore tab/space differences. Why does it matters?

**Comment by thegrb93** [comment]
The rest of the codebase uses tabs

**Comment by stepa2** [comment]
Changed

**Review by thegrb93 — APPROVED** [review]

**Comment by Fasteroid** [comment]
oh god

**Pull request merged**
