### PR TITLE
Fix null chars screwing up e2 networking

### PR DESCRIPTION
**Pull request by thegrb93**
Fixes: #2095

### CODE REVIEW

**Comment by Fasteroid** [comment]
starfall creator destroys e2 anti-steal glitch 2020 colourized

**Comment by thegrb93** [comment]
😈

**Comment by TheVayt** [comment]
I get this every time I use the tool
```[Wiremod] net.WriteData: Invalid length 0!
  1. Expression2Upload - lua/wire/stools/expression2.lua:83
   2. Upload - lua/wire/stools/expression2.lua:74
    3. PostMake - lua/wire/stools/expression2.lua:37
     4. LeftClick - lua/wire/tool_loader.lua:117
      5. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:240
```

**Comment by rAiZeNXD** [comment]
> I get this every time I use the tool
> 
> ```
>   1. Expression2Upload - lua/wire/stools/expression2.lua:83
>    2. Upload - lua/wire/stools/expression2.lua:74
>     3. PostMake - lua/wire/stools/expression2.lua:37
>      4. LeftClick - lua/wire/tool_loader.lua:117
>       5. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:240
> ```

same

**Comment by thegrb93** [comment]
https://github.com/wiremod/wire/pull/2111 fixes that

**Comment by Bryantdl7** [comment]
Your wisdom will help me work with my team and update you on what addon may be the culprit. I’ll be back in touch if I can find the offending addon with that piece of info.

**Pull request merged**
