### PR TITLE
Removed unused code

### PR DESCRIPTION
**Pull request by suunrider**

### CODE REVIEW

**Comment by immibis** [comment]
http://www.wiremod.com/forum/cpu-gpu-hi-speed-discussion-help/8159-emufox-complete-zcpu-zgpu-console-screen-emulator.html - looks like an abandoned project, so okay

**Comment by AbigailBuccaneer** [comment]
I remember EmuFox working brilliantly! @PhoenixBlack they're killing off your babies :(

**Comment by immibis** [comment]
@AbigailBuccaneer BlackPhoenix can re-add the code if it gets revived.

**Comment by TomyLobo** [comment]
I'd rather see him doing that on the EmuFox side where it belongs. Doesn't look like it's too hard to do anyway.

**Pull request merged**
