### PR TITLE
Add Highspeed Gates

### PR DESCRIPTION
**Pull request by its-suun**
* "Highspeed Write" Gate added
* "Highspeed Read" Gate added

### CODE REVIEW

**Comment by Divran** [comment]
Are you sure "Memory" is the best variable name for the wirelink input? Not sure what else to call it, though

**Comment by its-suun** [comment]
Don't know why "Memory" wouldn't fit. The input is just there to access the memory of something

**Comment by its-suun** [comment]
Merge?

**Comment by Divran** [comment]
I have nothing against this

@AbigailBuccaneer @TomyLobo and whoever else, thoughts?

**Comment by TomyLobo** [comment]
I think the name "Memory" is apt, unless you plan on adding input/output setting functionality or EGP functionality :D

**Comment by AbigailBuccaneer** [comment]
`"Memory"` is the port name that other entities use for similar purposes, so I have nothing against that. Unfortunately, those entities take an output of type `NORMAL` to get the entity that it's connected to [as a pre-Wirelink hack](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_dataplug.lua#L45), and before Wirelink this was the standard way to do such things. I'm a little concerned that adding these would clash with legacy functionality (/ make the legacy functionality more obvious by not supporting it here).

That being said, there's no easy way to have a `(NORMAL | WIRELINK)` type port, so I don't see any easy backwards-compatible resolution to the issue. Thoughts?

**Comment by its-suun** [comment]
In my opinion there should be a new type called `Memory` which is just there for accessing Memory. Wirelink doesn't quite fit for gates since it has access to inputs and outputs and egps. My solution wouldn't be backwards-compatible, but the use of `Normal` as memory link is pretty uncommon (i think, since everybody uses e2 anyway)

**Comment by its-suun** [comment]
Can this get merged? The described problem can be opened in a new issue

**Comment by Divran** [comment]
Don't see why not

**Comment by immibis** [comment]
Interesting addition @its-suun

**Comment by its-suun** [comment]
thanks

**Pull request merged**
