### PR TITLE
Remove e2doc, since it doesn't seem to work

### LINKED ISSUE #1377: e2doc console command does not work
<code><a href="https://github.com/wiremod/wire/blob/930023863d0000801c90b6612c10c966b94acc23/lua/entities/gmod_wire_expression2/core/e2doc.lua#L125-L150">e2doc</a></code> console command does not work.

Also, auto-complete function throws the following errors:
<pre>
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:140: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:140
</pre>

<pre>
[ERROR] addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:72: bad argument #1 to 'gmatch' (string expected, got nil)
  1. gmatch - [C]:-1
   2. e2doc - addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:72
    3. unknown - addons/wire/lua/entities/gmod_wire_expression2/core/e2doc.lua:133
     4. unknown - lua/includes/modules/concommand.lua:54
</pre>

### PR DESCRIPTION
**Pull request by Nebual**
Closes #1377

I think this generated E2 markup? I couldn't convince it to run - I think its supposed to be used like `e2doc custom/prop.lua`

### CODE REVIEW

**Comment by Divran** [comment]
I think someone on the discord fixed it up on their fork

**Comment by JanTuck** [comment]
I think it was @adosikas aka Gohidas, who was playing around with the e2docs.

**Comment by adosikas** [comment]
Yeah i have been doing a bit of work at https://github.com/adosikas/wire/tree/e2doc-comments

Example: https://github.com/adosikas/wire/wiki/E2:-Entity

**Comment by Nebual** [comment]
Ahh neat. On my phone currently, but looks better than nothing! Make a PR before all your comment changes get stale :)

**Comment by thegrb93** [comment]
What's this?

**Comment by Divran** [comment]
a thing meant to output an auto-generated E2 wiki. Since the E2 wiki is horribly outdated, this would be the easiest way to fix that. Someone just needs to fix it first.

**Pull request closed without merging**
