### PR TITLE
E2: Add "string=entity:steamID64()" function

### PR DESCRIPTION
**Pull request by CaptainPRICE**
This pull request (after merged) would add the following to Expression 2 gate:

new Functions:

Signature | Description
------------ | -------------
string=entity:steamID64() | Gets the Steam Community ID (aka Steam64) of the given player

### CODE REVIEW

**Comment by bigdogmat** [comment]
You don't need a comment above the function about what it does

**Comment by CaptainPRICE** [comment]
> You don't need a comment above the function about what it does

Okay then.

**Comment by TomyLobo** [comment]
Can you squash those commits?

**Comment by Divran** [comment]
>You don't need a comment above the function about what it does

no but it's helpful if the function name isn't self explanatory. It isn't necessary in this case though

**Comment by TomyLobo** [comment]
I know, but it's better if people write their own commit messages

**Pull request merged**
