### PR TITLE
Fix gpu switcher. Fixes: #1992

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by thegrb93** [comment]
Not sure if fixes all cases. @ShadowzOfTheDark mind testing this?

**Comment by ShadowzOfTheDark** [comment]
The error
[ERROR] addons/wire-fix-gpuswitcher/lua/wire/stools/gpulib_switcher.lua:61: attempt to call global 'MakeGPULibController' (a nil value)
  1. RightClick - addons/wire-fix-gpuswitcher/lua/wire/stools/gpulib_switcher.lua:61
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:263

Occurs when attempting to place the GPUSwitcher with the toolgun.

**Comment by thegrb93** [comment]
Ah, probably still had the function in my global table while testing. I'll fix that tonight.

**Comment by thegrb93** [comment]
@ShadowzOfTheDark can you try this now?

**Comment by ShadowzOfTheDark** [comment]
Still doesn't dupe properly.

AdvDupe2 Gives no errors, other than it couldn't weld the entity.

Garry dupe spits this in console:
[ERROR] addons/wire-fix-gpuswitcher/lua/wire/server/wirelib.lua:1018: attempt to index local 'Data' (a nil value)
  1. CreateEntityFromTable - addons/wire-fix-gpuswitcher/lua/wire/server/wirelib.lua:1018
   2. unknown - lua/includes/modules/duplicator.lua:723
    3. ProtectedCall - [C]:-1
     4. oldPaste - lua/includes/modules/duplicator.lua:723
      5. Paste - addons/wire-fix-gpuswitcher/lua/wire/server/wirelib.lua:1216
       6. LeftClick - gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator.lua:63
        7. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/shared.lua:240

AdvDupe1 returns this:
AdvDupeERROR: CreateEntity failed to make "gmod_wire_gpulib_controller", Error: addons/wire-fix-gpuswitcher/lua/wire/server/wirelib.lua:1018: attempt to index local 'Data' (a nil value)
stack traceback:
	addons/wire-fix-gpuswitcher/lua/wire/server/wirelib.lua:1018: in function <addons/wire-fix-gpuswitcher/lua/wire/server/wirelib.lua:1017>
	[C]: in function 'xpcall'
	lua/autorun/server/advdupe.lua:2603: in function 'CreateEntityFromTable'
	lua/autorun/server/advdupe.lua:2447: in function 'PasteEntity'
	lua/autorun/server/advdupe.lua:2038: in function 'Paste'
	lua/autorun/server/advdupe.lua:1984: in function 'NormPaste'
	lua/autorun/server/advdupe.lua:1954: in function <lua/autorun/server/advdupe.lua:1953>
	[C]: in function 'xpcall'
	lua/autorun/server/advdupe.lua:1736: in function 'v'
	lua/includes/modules/hook.lua:84: in function <lua/includes/modules/hook.lua:67>

**Comment by thegrb93** [comment]
Should be good now.

**Comment by TomyLobo** [comment]
holy shit, that hack you removed in the last commit :D

https://github.com/wiremod/wire/commit/69a53598d5cac9f1df2f3ac53e7222c74c246f9b#diff-456a736302c5d270f9b3020b5ee2a048R1125-R1169

I swear, it was necessary back then!

**Comment by TomyLobo** [comment]
But this totally explains why advdupe2 didn't work with this. I'd say it lacks that table that hack is looking for.

**Pull request merged**
