### PR TITLE
clientside lever

### PR DESCRIPTION
**Pull request by Divran**
todo:
* ~~Try to make it backwards compatible with old dupes~~
* ~~Make the lever arm render even when the lever base is out of view~~
* old lever saved its current value through dupe - do we want to keep this behavior? if yes, add it back in
* ~~remove commented-out old code~~

### CODE REVIEW

**Comment by Divran** [comment]
@Nebual old dupe fix might be a bit messy, take a look? dunno how else to do it honestly

**Comment by thegrb93** [comment]
Why max render distance? please no.

**Comment by thegrb93** [comment]
This math here could use a lot of optimization as well. I'll give it a look too.

**Comment by Divran** [comment]
> Why max render distance? please no.

why keep the clientside prop loaded all of the time? the range is so far that by the time you're that far away it's like 10 pixels tall or something anyway

> This math here could use a lot of optimization as well. I'll give it a look too.

yeah I didn't touch a lot of the lever related math, I dunno who wrote it

**Comment by thegrb93** [comment]
Because this is gmod, not mario64

**Comment by Divran** [comment]
image
max range 1024

image
max range 2048

are either of these good enough @thegrb93 ?

**Comment by thegrb93** [comment]
Because this is gmod, not mario64

**Comment by Divran** [comment]
it only runs the distance check once per second, although that was to reduce the impact of spawning and removing the entity more than the impact of a simple distance check

**Comment by thegrb93** [comment]
It also doesn't take into account that players can view through a camera or through a sniper scope. I'd just make it a clientside prop parented to the base.

**Comment by Divran** [comment]
alright changing it

**Comment by Nebual** [comment]
Seems to work fairly well! It converted my dupe successfully too (though it did warn that a weld constraint "failed", since the lever stick ain't real no more).

In my "4 hoverballs on a plate, with lever wired to ZVelocity" craft, it performed well, though I found it a bit tricky to start using the lever - it seems you need to aim pretty close to the base for the serverside Use to fire, which makes sense. 

I was able to get a clientside collision check to more reliably work 1372e3a46855b4790841c2b7eb9df6f8f5b1a23f , which can then send a net message to trigger a serverside Use() as normal - `git fetch && git cherry-pick 1372e3a46` if you want to add it

**Comment by Divran** [comment]
The "start using the lever" issue works flawlessly if the lever is the only thing nearby. You can even press use on the tip of the lever and it'll still catch it. But I did notice problems if other entities were nearby, such as if you place the lever on a prop, so a fix like yours is probably needed.

**Comment by Divran** [comment]
> though it did warn that a weld constraint "failed", since the lever stick ain't real no more

that shouldn't be the case since the conversion only happens after the entire dupe has finished pasting, due to the hook being used

**Comment by thegrb93** [comment]
Was working all day on stuff so too tired right now, but tomorrow I'll start looking at it.

**Comment by thegrb93** [comment]
Should be ready to merge to master after https://github.com/wiremod/wire/pull/2048 is merged.

**Pull request merged**
