### PR TITLE
Bone stuff

### PR DESCRIPTION
**Pull request by Fasteroid**
Tested on a local server, should be ready to merge:
image
For now I've only implemented getters as setters would have serious abuse potential (imagine the spiderlike abominations)
#2058

### CODE REVIEW

**Review by Fasteroid — COMMENTED** [review]
Vurv's @strict errors weren't descriptive enough for my liking—and two of them were flatout wrong.   This commit fixes those.

**Review by thegrb93 — APPROVED** [review]

**Comment by thegrb93** [comment]
There's no setters except for manipulateBonePosition which does brick the netgraph when used serverside.

**Comment by Fasteroid** [comment]
> Whats wrong with spiderlike abominations? 
I fear abuse such as this, which could could have server-disrupting potential:
```
for(I=1,20){
    holoBonePos(1,I,randvec() * 10000)
}
```
Then again, their funeral if they have holoModelAny on... lol

**Comment by Fasteroid** [comment]
GAH I wasn't ready for that!  Revert! Revert!

**Comment by thegrb93** [comment]
If the additional changes were added to this one, it wouldn't be merged for a long time.

**Pull request merged**
